/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

#include <stdafx.h>
#include "cnst_text.h" 

LPCWSTR LANG_DATA_FR[1665] = {
	L"",
	L"+",
	L"-",
	L"Ok",
	L"Annuler",
	L"Oui",
	L"Non",
	L"Recommencer",
	L"n/a",
	L"Fermer",
	L"Aide",
	L"Lancer",
	L"Info",
	L"Taille de la carte",
	L"Version de la carte",
	L"Auteur",
	L"Renvoyer",
	L"Construire",
	L"Recruter",
	L"N\u00E9cessite:",
	L"Co\u00FBt:",
	L"Guarde:",
	L"Visit\u00E9",
	L"Non visit\u00E9",
	L"Appartient \u00E0:",
	L"Aucun",
	L"Diviser",
	L"Echanger",
	L"Se rendre",
	L"Retraite",
	L"Charger",
	L"Sauvegarder",
	L"<...>",
	L"Charger une partie sauvegard\u00E9e:",
	L"Sauvegarder la partie:",
	L"S\u00E9lectionnez un sc\u00E9nario \u00E0 jouer:",
	L"Victoire",
	L"D\u00E9faite",
	L"Nom de la Carte",
	L"Combat Automatique",
	L"Vue d'ensemble du royaume",
	L"Carte du Puzzle",
	L"Menu Syst\u00E8me",
	L"Revenu Journalier:",
	L"Territoire Inconnu",
	L"Inoccup\u00E9",
	L"Pas de Taverne",
	L"S\u00E9lectionnez une Destination",
	L"Croissance",
	L"Disponible",
	L"Co\u00FBt par Unit\u00E9",
	L"Recruter",
	L"Co\u00FBt total",
	L"Points de magie",
	L"Niveau",
	L"Lvl",
	L"Exp\u00E9rience",
	L"Points de d\u00E9placement",
	L"Laisser des Gardes",
	L"Sauvegard\u00E9 \u00E0",
	L"Date de la Partie",
	L"Ressources du Royaume",
	L"Disponible \u00E0 la Vente",
	L"A travers un interstice vous voyez un ancien artefact. Malheureusement, celui-ci est gard\u00E9 par:",
	L"A votre grand d\u00E9sarroi, le %s est gard\u00E9 par:",
	L"Souhaitez vous combattre les gardes?",
	L"Enregistrement",
	L"ID de l'appareil",
	L"Cl\u00E9 d'enregistrement",
	L"Enregistrer",
	L"Plus tard",
	L"Enregistrement R\u00E9ussi",
	L"Echec de l'enregistrement",
	L"Le code utilis\u00E9 pour enregistrer Pocket Heroes est invalide.",
	L"Merci d'avoir achet\u00E9 le jeu Pocket Heroes!",
	L"Visitez le site officiel \u00E0 l'adresse www.pocketheroes.net pour acheter le jeu Pocket Heroes.",
	L"Achetez le jeu Pocket Heroes \u00E0 l'adresse www.pocketland.de",
	L"#FCCCApr\u00E8s votre achat sur #FFF6Handango#FCCC, vous recevrez un certificat. Pour terminer votre enregistrement, vous devrez activer votre copie sur le site officiel de www.pocketheroes.net",
	L"Son",
	L"D\u00E9sactiv\u00E9",
	L"Contr\u00F4les",
	L"Modifier les contr\u00F4les",
	L"Langue du jeu",
	L"Appuyez sur la touche souhait\u00E9e\u2026",
	L"- N/A -",
	L"Start",
	L"Haut",
	L"Bas",
	L"Gauche",
	L"Droite",
	L"Bouton #1",
	L"Bouton #2",
	L"Bouton #3",
	L"Bouton #4",
	L"Bouton #5",
	L"Bouton #6",
	L"Enregistrer",
	L"Parler",
	L"Terminer",
	L"Retour",
	L"Menu",
	L"Soft #1",
	L"Soft #2",
	L"Mode d'aide",
	L"Mode manuel",
	L"Carte d'ensemble",
	L"Minimiser",
	L"Capture d'\u00E9cran",
	L"Quicksave",
	L"Afficher le rappel de mvt.",
	L"Afficher la grille sur la carte",
	L"Afficher la grille de combat",
	L"Combat rapide",
	L"Afficher points de passage",
	L"Vue d'ensemble liss\u00E9e",
	L"Echelle de vue d'ensemble x4",
	L"Mode gaucher",
	L"Sauvegarde auto",
	L"Autozoom On Hold",
	L"Volume sonore",
	L"Niveau gamma",
	L"D\u00E9placement carte",
	L"Vitesse des H\u00E9ros",
	L"Vitesse de combat",
	L"Tr\u00E8s lent",
	L"Lent",
	L"Normal",
	L"rapide",
	L"Tr\u00E8s rapide",
	L"Jan",
	L"F\u00E9v",
	L"Mar",
	L"Avr",
	L"Mai",
	L"Jun",
	L"Jul",
	L"Aou",
	L"Sep",
	L"Oct",
	L"Nov",
	L"D\u00E9c",
	L"Votre partie actuelle sera perdue. Etes vous s\u00FBr de vouloir charger une autre partie?",
	L"Votre partie actuelle sera perdue. Etes vous s\u00FBr de vouloir recommencer le sc\u00E9nario?",
	L"Etes vous s\u00FBr de vouloir quitter?",
	L"Votre partie actuelle sera perdue. Etes vous s\u00FBr de vouloir retourner au menu principal?",
	L"L'emplacement s\u00E9lectionn\u00E9 est d\u00E9j\u00E0 utilis\u00E9. Souhaitez vous le remplacer?",
	L"Partie sauvegard\u00E9e...",
	L"Screenshot enregistr\u00E9...",
	L"D\u00E9sol\u00E9 - cette fonction n'est pas disponible dans la version actuelle.",
	L"Vous avez gagn\u00E9!",
	L"a atteint le niveau %d",
	L"#FFFF%s #S0#FDDD(%s niveau %d)",
	L"Tous les pr\u00E9requis pour ce b\u00E2timent sont remplis",
	L"D\u00E9j\u00E0 construit",
	L"Etes vous s\u00FBr de vouloir renvoyer cette arm\u00E9e?",
	L"Etes vous s\u00FBr de vouloir renvoyer ce h\u00E9ros?",
	L"Un groupe de %s en qu\u00EAte de gloire souhaite vous rejoindre. Les acceptez vous?",
	L"Les %s, impressionn\u00E9s par vos forces, commencent \u00E0 s'enfuir. Souhaitez vous les poursuivre et engager le combat? ",
	L"Votre H\u00E9ros peut apprendre l'une des comp\u00E9tences secondaires suivantes:",
	L"Votre H\u00E9ros a appris:",
	L"Que choisissez vous?",
	L"Faites de la place dans votre arm\u00E9e pour les %s.",
	L"Caract\u00E9ristiques des %s:",
	L"J'accepterai votre reddition et je vous laisserai repartir avec votre arm\u00E9e pour la somme de %d pi\u00E8ces d'or.",
	L"Il vous manque %d points d'exp\u00E9rience pour atteindre le prochain niveau.",
	L"F\u00E9licitation! Tous vos ennemis ont \u00E9t\u00E9 vaincus! Vous \u00EAtes victorieux!",
	L"Toutes vos troupes ont \u00E9t\u00E9 vaincues, et vous \u00EAtes banni de ces terres!",
	L"Le joueur %s a \u00E9t\u00E9 vaincu!",
	L"Il n'y a pas de place dans la garnison pour ces troupes.",
	L"Etes vous s\u00FBr de vouloir terminer votre tour?",
	L"Jetez donc un oeil \u00E0 nos marchandises. Si vous souhaitez en acqu\u00E9rir, cliquez sur l'objet qui vous int\u00E9resse.",
	L"Je peux vous offrir:",
	L"%s   pour   %s",
	L"Vous avez d\u00E9j\u00E0 quatre H\u00E9ros.",
	L"Il n'y a aucun H\u00E9ros de disponible dans cette taverne, revenez la semaine prochaine.",
	L"Ce sort n'affectera personne!",
	L"Pas assez de points de magie pour lancer ce sort.",
	L"Ce sort n\u00E9cessite la comp\u00E9tence %s au niveau %s.",
	L"Fait %d points de d\u00E9g\u00E2ts.",
	L"Les cr\u00E9atures souhaitent nous rejoindre!",
	L"Ces faibles cr\u00E9atures vont assur\u00E9ment fuir en nous voyant.",
	L"Je crains que ces cr\u00E9atures ne soient d'humeur \u00E0 combattre.",
	L"Aucun sort s\u00E9lectionn\u00E9",
	L"Votre H\u00E9ros est trop fatigu\u00E9 pour lancer ce sort aujourd'hui. R\u00E9essayez demain.",
	L"N\u00E9cessite un H\u00E9ros de niveau %d poss\u00E9dant la comp\u00E9tence %s.",
	L"N\u00E9cessite un H\u00E9ros de niveau %d.",
	L"N\u00E9cessite un H\u00E9ros poss\u00E9dant la comp\u00E9tence %s.",
	L"Tour du joueur %s.",
	L"Le joueur %s est attaqu\u00E9!",
	L"Vous auriez d\u00FB faire plus attention - vous \u00EAtes attaqu\u00E9!",
	L"Creuser \u00E0 la recherche d'un artifact prend une journ\u00E9e compl\u00E8te, r\u00E9essayez demain.",
	L"Essayez de chercher en terrain d\u00E9gag\u00E9.",
	L"F\u00E9licitations! Apr\u00E8s avoir pass\u00E9 de nombreuses heures \u00E0 creuser ici, votre H\u00E9ros a d\u00E9couvert la Couronne du Conqu\u00E9rant.",
	L"Rien ici. O\u00F9 cela peut-il bien se trouver?",
	L"Il y a sept types de ressources dans Pocket Heroes, qui sont utilis\u00E9es pour construire et am\u00E9liorer les ch\u00E2teaux, acheter des troupes et engager des H\u00E9ros. L'Or est la plus r\u00E9pandue, rien ne peut \u00EAtre fait sans. Le Bois et le Minerai sont utilis\u00E9s pour la plupart des b\u00E2timents. Les Gemmes, le Mercure, le Soufre et les cristaux sont de rares ressources magiques utilis\u00E9es pour les cr\u00E9atures et les b\u00E2timents les plus puissants.",
	L"L'Exp\u00E9rience permet \u00E0 vos H\u00E9ros de gagner des niveaux et d'am\u00E9liorer leurs comp\u00E9tences principales et secondaires.",
	L"Les Points de Magie sont n\u00E9cessaires pour lancer des sorts. Le nombre maximum de Points de Magie d'un H\u00E9ros est de 10 fois leur niveau de Connaissance. Certains \u00E9v\u00E8nements et certaines structures peuvent augmenter temporairement ce maximum.",
	L"Les points de d\u00E9placement d\u00E9terminent la distance que peut parcourir votre H\u00E9ros chaque jour. Celle-ci d\u00E9pend du type de terrain, des routes, ainsi que de son niveau dans les comp\u00E9tences Logistique et Orientation. Certains sites, \u00E8venements ou artefacts peuvent aussi augmenter le nombre de points de mouvement.",
	L"La comp\u00E9tence d'Attaque est un bonus ajout\u00E9 \u00E0 l'attaque de base des troupes que votre H\u00E9ros dirige, leur permettant d'infliger plus de d\u00E9g\u00E2ts en combat.",
	L"La comp\u00E9tence de D\u00E9fense est un bonus ajout\u00E9 \u00E0 la d\u00E9fense de base des troupes que votre H\u00E9ros dirige, leur permettant de subir moins de d\u00E9g\u00E2ts en combat.",
	L"La Magie d\u00E9termine la dur\u00E9e ou la puissance d'un sort.",
	L"La Connaissance d\u00E9termine le nombre de Points de Magie dont dispose votre H\u00E9ros. Hormis cas exceptionnel, un H\u00E9ros est limit\u00E9 \u00E0 10 Points de Magie par niveau de Connaissance.",
	L"Une Chance \u00E9lev\u00E9e permet \u00E0 vos troupes d'infliger des d\u00E9g\u00E2ts doubl\u00E9s en combat.",
	L"Avec une Chance neutre, les attaques de vos troupes ne sont pas modi\u00E9es.",
	L"Les troupes ayant une Chance faible n'infligent que la moiti\u00E9 des d\u00E9g\u00E2ts en combat.",
	L"Un Moral \u00E9lev\u00E9 peut permettre \u00E0 une unit\u00E9 d'attaquer une fois suppl\u00E9mentaire dans le tour.",
	L"Un Moral neutre neutralise pour les unit\u00E9s les chances d'attaquer une fois de plus et les risques de se figer.",
	L"Un Moral faible peut causer \u00E0 une unit\u00E9 de se retrouver fig\u00E9e au combat, perdant une chance d'attaquer.",
	L"Effacer le tableau de scores va supprimer vos performances. Etes vous s\u00FBr de vouloir effacer les scores?",
	L"Nouvelle Semaine",
	L"Nouveau Mois",
	L"Les astrologues proclament le mois des %s.",
	L"Les astrologues proclament le mois de la PESTE!",
	L"Les astrologues proclament la semaine des %s.",
	L"Toutes les comunaut\u00E9s augmentent leur population.",
	L"Toutes les populations sont divis\u00E9es de moiti\u00E9e.",
	L"La population des %s double!",
	L"La population des %s augmente de +5.",
	L"Ecureuils",
	L"Lapins",
	L"Chiens de prairie",
	L"Blaireaux",
	L"Rats",
	L"Aigles",
	L"Belettes",
	L"Corbeaux",
	L"Mangoustes",
	L"Chiens",
	L"Fourmiliers",
	L"L\u00E9zards",
	L"Tortues",
	L"H\u00E9rissons",
	L"Condors",
	L"Sauterelles",
	L"Fourmis",
	L"Coccinelles",
	L"Araign\u00E9es",
	L"Papillons",
	L"Bourdons",
	L"Criquets",
	L"Vers de Terre",
	L"Frelons",
	L"Cafards",
	L"Pertes au champ de bataille",
	L"Attaquant",
	L"D\u00E9fenseur",
	L"Journal du combat",
	L"Leur moral \u00E9lev\u00E9 permet aux %s de relancer une attaque.",
	L"Leur moral bas empeche les %s d'agir.",
	L"L'\u00E9toile de la chance brille sur les %s",
	L"La malchance s'abat sur les %s",
	L"Tour %d",
	L"Attaque %s",
	L"Tire sur %s",
	L" (%d points de d\u00E9g\u00E2ts)",
	L" (%d-%d points de d\u00E9g\u00E2ts)",
	L"Les %s font %d points de d\u00E9g\u00E2ts.",
	L"%d %s p\u00E9rissent.",
	L"Les %s attendent un moment plus opportun pour attaquer.",
	L"Les %s se mettent en position d\u00E9fensive et gagnent +%d \u00E0 leur comp\u00E9tence de d\u00E9fense.",
	L"La tour fait %d points de d\u00E9g\u00E2ts.",
	L"Les douves font %d points de d\u00E9g\u00E2ts.",
	L"%s d\u00E9truisent la moiti\u00E9 des troupes ennemies!",
	L"Lance \"%s\".",
	L"Lance \"%s\" sur %s.",
	L"%s lance \"%s\".",
	L"%s lance \"%s\" sur %s.",
	L"Le sort %s fait %d points de d\u00E9g\u00E2ts.",
	L"Les %s r\u00E9sistent au sort.",
	L"Vous avez r\u00E9cup\u00E9r\u00E9 un artefact ennemi!",
	L"Vous avez r\u00E9cup\u00E9r\u00E9 %d artefacts ennemis!",
	L"Une victoire glorieuse!",
	L"L'ennemi a fui!",
	L"L'ennemi s'est rendu!",
	L"Pour sa valeur au combat, %s re\u00E7oit %d points d'exp\u00E9rience.",
	L"Vos forces subissent une am\u00E8re d\u00E9faite, et %s abandonne votre cause.",
	L"Vos forces subissent une am\u00E8re d\u00E9faite.",
	L"%s fuit l\u00E2chement le champ de bataille.",
	L"%s se rend \u00E0 l'ennemi et s'en va l\u00E2chement.",
	L"%s poss\u00E8de la Sph\u00E8re de N\u00E9gation, un ancien artefact qui emp\u00EAche de lancer des sorts magiques.",
	L"%s poss\u00E8de les Cha\u00EEnes de Guerre. Vous ne pouvez ni fuir, ni vous rendre!",
	L"Vous n'avez pas assez d'or!",
	L"A l'aide des t\u00E9n\u00E9breux arts de la N\u00E9cromancie, vous \u00EAtes capable de ranimer %d des morts ennemis pour vous servir sous la forme de squelettes.",
	L"Petite",
	L"Moyenne",
	L"Grande",
	L"Tr\u00E8s Grande",
	L"S",
	L"M",
	L"L",
	L"XL",
	L"Niveau",
	L"Terrain",
	L"Date",
	L"Jours",
	L"Score",
	L"Niveau de Difficult\u00E9",
	L"Facile",
	L"Normal",
	L"Difficile",
	L"Expert",
	L"Impossible",
	L"Single Player",
	L"Nouvelle Partie",
	L"Multiplayer",
	L"Online Game",
	L"Help",
	L"Tutorial",
	L"Charger une Sauvegarde",
	L"Sauvegarder la Partie",
	L"Tableau d'Honneur",
	L"Remerciements",
	L"R\u00E9glages de la Partie",
	L"Red\u00E9marrer le sc\u00E9nario",
	L"Retourner au Menu",
	L"Quitter",
	L"Retourner \u00E0 la Partie",
	L"Hot-Seat",
	L"Nombre de Villes",
	L"Nombre de H\u00E9ros",
	L"Ressources",
	L"Ob\u00E9lisques trouv\u00E9es",
	L"Artefacts",
	L"Forces de l'Arm\u00E9e",
	L"Revenus",
	L"Eau",
	L"Sable",
	L"Terre",
	L"Herbe",
	L"Marais",
	L"Lave",
	L"Terre D\u00E9vast\u00E9e",
	L"D\u00E9sert",
	L"Neige",
	L"D\u00E9sert",
	L"Route",
	L"Lande",
	L"C\u00F4te",
	L"Lac",
	L"Joueur",
	L"Joueur",
	L"Rouge",
	L"Vert",
	L"Bleu",
	L"Cyan",
	L"Violet",
	L"Jaune",
	L"Rouge",
	L"Vert",
	L"Bleu",
	L"Cyan",
	L"Violet",
	L"Jaune",
	L"Non D\u00E9fini",
	L"Humain",
	L"Ordinateur",
	L"Seulement Humain",
	L"Seulement Ordinateur",
	L"Humain ou Ordinateur",
	L"Date",
	L"Mois",
	L"Semaine",
	L"Jour",
	L"M",
	L"S",
	L"J",
	L"Attaque",
	L"D\u00E9fense",
	L"Magie",
	L"Conn.",
	L"Tirs",
	L"D\u00E9g\u00E2ts",
	L"Vie",
	L"Vitesse",
	L"Quantit\u00E9",
	L"Moral",
	L"Chance",
	L"Comp\u00E9tence d'Attaque",
	L"Comp\u00E9tence de D\u00E9fense",
	L"Magie",
	L"Connaissance",
	L"Tirs",
	L"D\u00E9g\u00E2ts",
	L"Points de Vie",
	L"Vitesse",
	L"Quantit\u00E9",
	L"Moral",
	L"Chance",
	L"Gestion",
	L"Commandement",
	L"Chance",
	L"Diplomatie",
	L"Magie de l'Air",
	L"Magie de la Terre",
	L"Magie du Feu",
	L"Magie de l'Eau",
	L"Sagesse",
	L"N\u00E9cromancie",
	L"Mysticisme",
	L"Intelligence",
	L"R\u00E9sistance",
	L"Sorcellerie",
	L"Apprentissage",
	L"Eclaireur",
	L"Logistique",
	L"Orientation",
	L"Tir \u00E0 l'arc",
	L"Ballistique",
	L"Attaque",
	L"Armurier",
	L"Le H\u00E9ros contribue \u00E0 votre cause \u00E0 hauteur de 250 pi\u00E8ces d'or par jour.",
	L"Le H\u00E9ros contribue \u00E0 votre cause \u00E0 hauteur de 500 pi\u00E8ces d'or par jour.",
	L"Le H\u00E9ros contribue \u00E0 votre cause \u00E0 hauteur de 1000 pi\u00E8ces d'or par jour.",
	L"Augmente de 1 le moral des troupes de votre H\u00E9ros.",
	L"Augmente de 2 le moral des troupes de votre H\u00E9ros.",
	L"Augmente de 3 le moral des troupes de votre H\u00E9ros.",
	L"Augmente de 1 la chance de votre H\u00E9ros.",
	L"Augmente de 2 la chance de votre H\u00E9ros.",
	L"Augmente de 3 la chance de votre H\u00E9ros.",
	L"Vous permet de n\u00E9gocier avec les monstres qui sont plus faibles que votre groupe, et r\u00E9duit le co\u00FBt de la reddition de 20%.",
	L"Vous permet de n\u00E9gocier avec les monstres qui sont plus faibles que votre groupe, et r\u00E9duit le co\u00FBt de la reddition de 40%.",
	L"Vous permet de n\u00E9gocier avec les monstres qui sont plus faibles que votre groupe, et r\u00E9duit le co\u00FBt de la reddition de 60%.",
	L"La Magie de l'Air Basique permet au H\u00E9ros de lancer les sorts de l'Air \u00E0 un co\u00FBt r\u00E9duit.",
	L"La Magie de l'Air Avanc\u00E9e permet au H\u00E9ros de lancer les sorts de l'Air \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 accrue.",
	L"La Magie de l'Air Experte permet au H\u00E9ros de lancer les sorts de l'Air \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 maximale.",
	L"La Magie de la Terre Basique permet au H\u00E9ros de lancer les sorts de la Terre \u00E0 un co\u00FBt r\u00E9duit.",
	L"La Magie de la Terre Avanc\u00E9e permet au H\u00E9ros de lancer les sorts de la Terre \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 accrue.",
	L"La Magie de la Terre Experte permet au H\u00E9ros de lancer les sorts de la Terre \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 maximale.",
	L"La Magie du Feu Basique permet au H\u00E9ros de lancer les sorts du Feu \u00E0 un co\u00FBt r\u00E9duit.",
	L"La Magie du Feu Avanc\u00E9e permet au H\u00E9ros de lancer les sorts du Feu \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 accrue.",
	L"La Magie du Feu Experte permet au H\u00E9ros de lancer les sorts du Feu \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 maximale.",
	L"La Magie de l'Eau Basique permet au H\u00E9ros de lancer les sorts de l'Eau \u00E0 un co\u00FBt r\u00E9duit.",
	L"La Magie de l'Eau Avanc\u00E9e permet au H\u00E9ros de lancer les sorts de l'Eau \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 accrue.",
	L"La Magie de l'Eau Experte permet au H\u00E9ros de lancer les sorts de l'Eau \u00E0 un co\u00FBt r\u00E9duit et avec une efficacit\u00E9 maximale.",
	L"Permet \u00E0 votre H\u00E9ros d'apprendre les sorts de Troisi\u00E8me niveau.",
	L"Permet \u00E0 votre H\u00E9ros d'apprendre les sorts de Quatri\u00E8me niveau.",
	L"Permet \u00E0 votre H\u00E9ros d'apprendre les sorts de Cinqui\u00E8me niveau.",
	L"Permet de ranimer 10% des cr\u00E9atures tu\u00E9es au combat sous la forme de Squelettes.",
	L"Permet de ranimer 20% des cr\u00E9atures tu\u00E9es au combat sous la forme de Squelettes.",
	L"Permet de ranimer 30% des cr\u00E9atures tu\u00E9es au combat sous la forme de Squelettes.",
	L"Permet \u00E0 votre H\u00E9ros de r\u00E9g\u00E9n\u00E9rer 2 Points de Magie par jour.",
	L"Permet \u00E0 votre H\u00E9ros de r\u00E9g\u00E9n\u00E9rer 4 Points de Magie par jour.",
	L"Permet \u00E0 votre H\u00E9ros de r\u00E9g\u00E9n\u00E9rer 6 Points de Magie par jour.",
	L"Augmente de 25% le nombre maximum normal de Points de Magie de votre H\u00E9ros.",
	L"Augmente de 50% le nombre maximum normal de Points de Magie de votre H\u00E9ros.",
	L"Double le nombre maximum normal de Points de Magie de votre H\u00E9ros.",
	L"Fait b\u00E9n\u00E9ficier les troupes du H\u00E9ros de 5% de r\u00E9sistance \u00E0 la magie.",
	L"Fait b\u00E9n\u00E9ficier les troupes du H\u00E9ros de 10% de r\u00E9sistance \u00E0 la magie.",
	L"Fait b\u00E9n\u00E9ficier les troupes du H\u00E9ros de 20% de r\u00E9sistance \u00E0 la magie.",
	L"Les sorts du H\u00E9ros infligent 5% de d\u00E9g\u00E2ts suppl\u00E9mentaire en combat.",
	L"Les sorts du H\u00E9ros infligent 10% de d\u00E9g\u00E2ts suppl\u00E9mentaire en combat.",
	L"Les sorts du H\u00E9ros infligent 15% de d\u00E9g\u00E2ts suppl\u00E9mentaire en combat.",
	L"Augmente de 5% l'exp\u00E9rience gagn\u00E9e par le H\u00E9ros.",
	L"Augmente de 10% l'exp\u00E9rience gagn\u00E9e par le H\u00E9ros.",
	L"Augmente de 15% l'exp\u00E9rience gagn\u00E9e par le H\u00E9ros.",
	L"Permet au hero de voir 2 carr\u00E9s de plus dans le brouillard.",
	L"Permet au hero de voir 4 carr\u00E9s de plus dans le brouillard.",
	L"Permet au hero de voir 6 carr\u00E9s de plus dans le brouillard.",
	L"Augmente de 10% les points de d\u00E9placement sur terre de votre H\u00E9ros.",
	L"Augmente de 20% les points de d\u00E9placement sur terre de votre H\u00E9ros.",
	L"Augmente de 30% les points de d\u00E9placement sur terre de votre H\u00E9ros.",
	L"R\u00E9duit de 25% la p\u00E9nalit\u00E9 de d\u00E9placement sur terrain difficile.",
	L"R\u00E9duit de 50% la p\u00E9nalit\u00E9 de d\u00E9placement sur terrain difficile.",
	L"R\u00E9duit de 75% la p\u00E9nalit\u00E9 de d\u00E9placement sur terrain difficile.",
	L"Augmente de 10% les d\u00E9g\u00E2ts des attaques \u00E0 distance.",
	L"Augmente de 25% les d\u00E9g\u00E2ts des attaques \u00E0 distance.",
	L"Augmente de 50% les d\u00E9g\u00E2ts des attaques \u00E0 distance.",
	L"Permet d'effectuer un tir vis\u00E9 avec d\u00E9g\u00E2ts augment\u00E9s.",
	L"Permet d'effectuer deux tirs vis\u00E9s avec d\u00E9g\u00E2ts augment\u00E9s.",
	L"Permet d'effectuer deux tirs vis\u00E9s avec un maximum de d\u00E9g\u00E2ts.",
	L"Augmente de 10% les d\u00E9g\u00E2ts des attaques au corps \u00E0 corps.",
	L"Augmente de 20% les d\u00E9g\u00E2ts des attaques au corps \u00E0 corps.",
	L"Augmente de 30% les d\u00E9g\u00E2ts des attaques au corps \u00E0 corps.",
	L"R\u00E9duit de 5% tous les d\u00E9g\u00E2ts inflig\u00E9s aux troupes du H\u00E9ros.",
	L"R\u00E9duit de 10% tous les d\u00E9g\u00E2ts inflig\u00E9s aux troupes du H\u00E9ros.",
	L"R\u00E9duit de 15% tous les d\u00E9g\u00E2ts inflig\u00E9s aux troupes du H\u00E9ros.",
	L"Basique",
	L"Avanc\u00E9",
	L"Expert",
	L"Or",
	L"Minerai",
	L"Bois",
	L"Mercure",
	L"Gemmes",
	L"Cristal",
	L"Soufre",
	L"Ressource al\u00E9atoire",
	L"Tas d'Or",
	L"Tas de Minerai",
	L"Cord\u00E9e de Bois",
	L"Bouteille de Mercure",
	L"Tas de Gemmes",
	L"Tas de Cristaux",
	L"Tas de Soufre",
	L"Cristal de Magie",
	L"Feu de Camp",
	L"Coffre au Tr\u00E9sor",
	L"Lampe",
	L"Parchemin de Sort",
	L"Artefact",
	L"Garde",
	L"Alors que vous serrez la bride de votre cheval, un garde s'approche de vous et vous dis \u00ABBienvenue. J'ai \u00E9t\u00E9 inform\u00E9 de votre arriv\u00E9e. Voulez-vous passer d\u00E8s maintenant?\u00BB",
	L"\u00AB\u00A0Personne ne m'a pr\u00E9venu de votre arriv\u00E9e,\u00A0\u00BB dit le Garde Fronti\u00E8re. \u00AB\u00A0Je ne peux pas vous laisser passer. Vous devriez peut-\u00EAtre commencer par chercher la Tente du Gardien des Cl\u00E9s.\u00A0\u00BB",
	L"Apr\u00E8s une fouille minutieuse de la zone, vous trouvez un tr\u00E9sor cach\u00E9. Vous pouvez prendre l'or ou le redistribuer aux paysans pour gagner de l'exp\u00E9rience.",
	L"Vous trouvez un parchemin sur lequel est inscrit le sort %s.",
	L"Ev\u00E8nement",
	L"",
	L"Al\u00E9atoire",
	L"Al\u00E9atoire (Niveau 1)",
	L"Al\u00E9atoire (Niveau 2)",
	L"Al\u00E9atoire (Niveau 3)",
	L"Al\u00E9atoire (Niveau 4)",
	L"Al\u00E9atoire (Niveau 5)",
	L"Al\u00E9atoire (Niveau 6)",
	L"Al\u00E9atoire",
	L"Al\u00E9atoire (Niveau 1)",
	L"Al\u00E9atoire (Niveau 2)",
	L"Al\u00E9atoire (Niveau 3)",
	L"Al\u00E9atoire (Niveau 4)",
	L"Trou",
	L"Interstice",
	L"Squelette",
	L"Fleurs",
	L"Champignons",
	L"Pierre",
	L"Souche",
	L"Buche",
	L"Cactus",
	L"Broussailles",
	L"Arbres",
	L"Palmier",
	L"Pin",
	L"Ch\u00EAne",
	L"Arbre Mort",
	L"Volcan",
	L"Montagne",
	L"Lac",
	L"Mur",
	L"Route de Poussi\u00E8re",
	L"Route de Pierre",
	L"Route de Pierre",
	L"Rivi\u00E8re",
	L"Coul\u00E9e de lave",
	L"",
	L"Pierre phosphorescente",
	L"Panneau en bois",
	L"Tour de Garde",
	L"Temple des M\u00E9duses",
	L"Carriole de rodeur",
	L"Tente du D\u00E9sert",
	L"Maison Hant\u00E9e",
	L"Fontaine de Pierre",
	L"Belv\u00E9d\u00E8re",
	L"Arbre de la Connaissance",
	L"Monolithe",
	L"Moulin \u00E0 Vent",
	L"Sanctuaire du Premier Cercle",
	L"Sanctuaire du Second Cercle",
	L"Sanctuaire du Troisi\u00E8me Cercle",
	L"Etables",
	L"Statue",
	L"Trinit\u00E9",
	L"Fontaine",
	L"Temple",
	L"Ep\u00E9e dans la Pierre",
	L"Fort",
	L"Forge",
	L"Cercle de Pierres",
	L"Rocher magique",
	L"Statue du Proph\u00E8te",
	L"Ar\u00E8ne",
	L"Biblioth\u00E8que",
	L"Ob\u00E9lisque",
	L"Source Magique",
	L"Jardin de la Connaissance",
	L"Cabane de Sorci\u00E8re",
	L"\u00C9pave",
	L"Caverne de Glace",
	L"Pyramide",
	L"Temple de Inti",
	L"Tr\u00E9sor des Ogres",
	L"Tr\u00E9sor des Mages",
	L"Tr\u00E9sor des Hydres",
	L"Tr\u00E9sor des M\u00E9duses",
	L"Tr\u00E9sor des Gargouilles",
	L"Tr\u00E9sor des Druides",
	L"Citadelle des Mages",
	L"Abbaye des Moines",
	L"Mausol\u00E9e",
	L"Ecole de Magie",
	L"Chutes du P\u00E9gase",
	L"Tani\u00E8re du Loup Blanc",
	L"Grotte de Warg",
	L"Sarg",
	L"Vampir Sarg",
	L"Wolfsh\u00F6hle alt",
	L"Wildscheinh\u00F6hle alt",
	L"Schwertk\u00E4mpfer Arsenal alt",
	L"Halflingh\u00FCtte alt",
	L"Factice",
	L"Tente du Gardien des Cl\u00E9s",
	L"Fonderie",
	L"Adobe des Ogres",
	L"Sarcophage des Momies",
	L"Propri\u00E9t\u00E9 des Elfes",
	L"Dolmen des Druides",
	L"Nid des Griffins",
	L"Boire au puit a restaur\u00E9 vos points de magie.",
	L"Un vieux chevalier appara\u00EEt au pied du belv\u00E9d\u00E8re. \u00ABMon seigneur, je vous enseignerai tout ce que je connais pour vous aider dans vos voyages.\u00BB",
	L"En vous voyant approcher, l'arbre ouvre ses yeux avec joie. \u00AB\u00A0Ah, un aventurier! Permettez moi de vous enseigner une petite partie de ce que j'ai appris au fil des ann\u00E9es.\u00A0\u00BB",
	L"En vous voyant approcher, les monolithe se met \u00E0 briller. Vous r\u00E9ussissez \u00E0 d\u00E9chiffrer les symboles grav\u00E9s sur sa surface.",
	L"Le gardien du moulin vous annonce: \u00AB\u00A0Monseigneur, j'ai travaill\u00E9 tr\u00E8s dur pour vous fournir ces ressources, revenez la semaine prochaine pour en avoir plus.\u00A0\u00BB",
	L"Vous approchez d'un petit autel entour\u00E9 par quelques moines novices. En \u00E9change de votre protection, ils acceptent de vous enseigner un sort simple - ",
	L"Vous approchez d'un autel d\u00E9cor\u00E9 entour\u00E9 par quelques moines bedonnants. En \u00E9change de votre protection, ils acceptent de vous enseigner un sort - ",
	L"Vous approchez d'un autel luxueux entour\u00E9 par des grands pr\u00EAtres. En \u00E9change de votre protection, ils acceptent de vous enseigner un sort complexe - ",
	L"Alors que vous approchez des \u00E9curies, le maitre palefrenier apparait, tenant la bride d'un magnifique cheval de guerre. \u00ABCet \u00E9talon vous aidera \u00E0 aller plus vite dans vos d\u00E9placements. H\u00E9las, son endurance diminuera avec l'usage, et vous devrez revenir chaque semaine pour une nouvelle monture.\u00BB",
	L"Vous avez trouv\u00E9 une ancienne statue de pierre \u00E9rod\u00E9e par les \u00E9l\u00E9ments. L'embrasser doit vous apporter joie et chance, ce que vous faites. La pierre est extr\u00EAmement froide au toucher.",
	L"Voici tout ce que j'ai r\u00E9uni cette semaine. Utilisez cet or avec sagesse.",
	L"Alors que vous buvez l'eau fra\u00EEche, vous obtenez de la chance pour votre prochaine bataille.",
	L"Une visite et une pri\u00E8re au temple augmentent le moral de vos troupes.",
	L"Pendant des heures, vous tentez de sortir l'\u00E9p\u00E9e de la roche, en vain... Mais ne soyez pas d\u00E9\u00E7u: votre arm\u00E9e s'est bien repos\u00E9e pendant que vous vous exerciez!",
	L"Pendant les heures pass\u00E9es au fort, le ma\u00EEtre vous montre une nouvelle technique de d\u00E9fense.",
	L"Vous approchez d'une forge... Vous entrez et voyez un forgeron au travail. Il pose son marteau et dit: \u00AB je peux r\u00E9parer votre armure.\u00BB",
	L"Vous avez trouv\u00E9 un groupe de druides adorant leurs \u00E9tranges monticules de pierre. Silencieusement, ils vous enseignent de nouvelles techniques de magie.",
	L"Vous avez trouv\u00E9 un groupe de pa\u00EFens adorant une \u00E9trange pri\u00E8re scintillante. Vous vous joignez \u00E0 eux. Silencieusement, ils vous enseignent de nouvelles techniques de magie.\"",
	L"Vous touchez la statue du proph\u00E8te et vous vous sentez devenir plus puissant.",
	L"Vous entrez dans l'ar\u00E8ne et vous retrouvez face \u00E0 des lions affam\u00E9s. Sous les acclamations de la foule, vous les ma\u00EEtrisez rapidement. Impressionn\u00E9 par votre comp\u00E9tence, un vieux formateur de gladiateurs accepte de vous entra\u00EEner en attaque et en d\u00E9fense.",
	L"Le responsable vous accepte dans la Bibliotheque de l'Illumination. Vous apprenez beaucoup durant votre bref s\u00E9jour.",
	L"Vous arrivez pr\u00E8s d'une ob\u00E9lisque faite d'un genre de pierre que vous n'aviez jamais vu avant. En la fixant intens\u00E9ment, la surface lisse change soudain et laisse paraitre une inscription. L'inscription est un morceau d'une carte ancienne. Vous vous empressez de les recopier.",
	L"Boire \u00E0 la source remplit votre sang de magie! Vous obtenez deux fois plus de points de magie en r\u00E9serve.",
	L"Un moine assis au centre d'un jardin vous invite \u00E0 m\u00E9diter avec lui. Vous l'accompagnez et, apr\u00E8s un court moment, vous vous sentez illumin\u00E9.",
	L"Le responsable de cette tente du ma\u00EEtre des clef semble heureux de vous voir. \u00ABHa! finalement quelqu'un de valable,\u00BB dit il. \u00ABJe vais imm\u00E9diatement faire savoir au garde fronti\u00E8re que vous \u00EAtes autoris\u00E9s \u00E0 passer.\u00BB",
	L"Boire une seconde fois au puit en une semaine ne vous aidera pas.",
	L"Un vieux chevalier apparait au pied du belv\u00E9d\u00E8re. \"Je suis navr\u00E9, mon seigneur, je vous ai enseign\u00E9 tout ce que je pouvais.\u00BB",
	L"A votre approche, l'arbre ouvre ses yeux avec plaisir. \u00ABQu'il est agr\u00E9able de te revoir, mon apprenti. J'esp\u00E8re que mon enseignement t'a aid\u00E9.\u00BB",
	L"A votre approche, la lumi\u00E8re du monolithe s'\u00E9teind peu \u00E0 peu.",
	L"Le gardien du moulin annonce: \"Messire, je suis d\u00E9sol\u00E9, il n'y a plus de resources disponibles actuellement. S'il vous plait, revenez la semaine prochaine.\u00BB",
	L"Le ma\u00EEtre palefrenier s'approche et dis: \u00ABVous avez d\u00E9j\u00E0 un fier \u00E9talon.\u00BB",
	L"Vous avez trouv\u00E9 une ancienne statue de pierre \u00E9rod\u00E9e par les \u00E9l\u00E9ments. Elle est sens\u00E9e apporter chance et joie aux visiteurs, mais comme les \u00E9toiles sont d\u00E9j\u00E0 sur vous, il ne se passe rien.",
	L"Je n'ai plpus d'or pour vous. Revenez la semaine prochaine.",
	L"Vous buvez \u00E0 la fontaine enchant\u00E9e, mais rien ne se passe.",
	L"Il ne sert \u00E0 rien de prier deux fois avant la bataille.",
	L"L'\u00E9p\u00E9e est prise dans la roche! Il ne sert \u00E0 rien de tenter de l'en sortir!",
	L"Je vous ai d\u00E9j\u00E0 appris tout ce que je savais. Je ne veux plus perdre mon temps avec vous, alors sortez!",
	L"Vous approchez d'une forge... Vous entrez et voyez un forgeron au travail. Il examine votre bouclier, et dit: \u00ABCe bouclier n'a pas besoin de r\u00E9paration. J'ai fait tout ce que je pouvais.\u00BB",
	L"Vous avez trouv\u00E9 un groupe de druides adorant leurs \u00E9tranges monticules de pierre. Silencieusement, ils vous \u00E9cartent, indiquant qu'ils n'ont rien de nouveau \u00E0 vous enseigner.",
	L"Vous avez trouv\u00E9 un groupe de pa\u00EFens adorant une \u00E9trange pri\u00E8re scintillante. Silencieusement, ils vous \u00E9cartent, indiquant qu'ils n'ont rien de nouveau \u00E0 vous enseigner.",
	L"Vous touchez la statue, mais rien ne se passe. Vous avancez votre main pour la toucher une seconde fois, et la statue commence soudainement \u00E0 parler: \u00ABJe vous ai donn\u00E9 toute ma magie, mais vous continuez \u00E0 m'importuner!? Partez!\u00BB",
	L"Les gardes de l'ar\u00E8ne vous emp\u00EAchent d'entrer. \u00ABVous avez d\u00E9j\u00E0 battu nos meilleurs. Partez d'ici maintenant.\u00BB",
	L"En vous reconnaissant, le responsable refuse de vous admettre. \u00ABLa Librairie de l'Illumination,\u00BB dit il, \u00ABne peut etre consult\u00E9e qu'une unique fois\u00BB.",
	L"Vous vous \u00EAtes d\u00E9j\u00E0 rendu \u00E0 cet ob\u00E9lisque.",
	L"La source magique ne se r\u00E9g\u00E9n\u00E8re qu'une fois par semaine, et quelqu'un y a d\u00E9j\u00E0 bu cette semaine.",
	L"Vous entrez dans le jardin, et le moine, en vous reconnaissant, dit, \u00ABMon fils, la b\u00E9n\u00E9diction de la connaissance n'arrive qu'une seule fois dans la vie d'un homme.\u00BB",
	L"Le responsable de cette tente du maitre des clefs vous reconna\u00EEt \u00E0 votre approche. \u00ABJ'ai d\u00E9j\u00E0 demand\u00E9 que l'on vous laisse passer,\u00BB dit il. \u00ABPartez.\u00BB",
	L"Malheureusement, vous n'avez pas la sagesse n\u00E9cessaire pour comprendre le sort et vous \u00EAtes incapable de l'apprendre.",
	L"Une vielle sorci\u00E8re vivant dans une \u00E9trange hutte vous accueille, vous enseignant %s pour des raisons encore myst\u00E9rieuses.",
	L"Vous approchez de l'ancienne hutte et observez une sorci\u00E8re \u00E0 l'int\u00E9rieur en train d'\u00E9tudier un ancien volume de %s. Alors que vous approchez, elle se tourne et parle. \u00ABVous savez d\u00E9j\u00E0 tout ce que je peux vous apprendre. Je ne peux rien faire de plus pour vous.\u00BB",
	L"Vous approchez de l'ancienne hutte et observez une sorci\u00E8re \u00E0 l'int\u00E9rieur en train d'\u00E9tudier un ancien volume de %s. Alors que vous approchez, elle se tourne et r\u00E8gle son monocle sur vous. \u00ABHA!\u00BB hurle t'elle, \u00ABComment pourrais-je enseigner de nouveaux trucs \u00E0 quelqu'un d'aussi intelligent que vous?\u00BB",
	L"Voulez vous recruter des %s?",
	L"%d %s rejoignent votre arm\u00E9e.",
	L"Il n'y a pas de %s \u00E0 recruter ici.",
	L"Vous trouvez ce qui f\u00FBt un %s, mais il a \u00E9t\u00E9 d\u00E9sert\u00E9 depuis longtemps.",
	L"Apr\u00E8s avoir vaincu les guardes, vous d\u00E9couvrez:",
	L"Sens-Unique (entr\u00E9e)",
	L"Sens-Unique (Sortie)",
	L"Double-Sens",
	L"Cette structure est vraisemblablement une porte de voyage, mais elle semble ne plus fonctionner.",
	L"Tour d'Eclaireur",
	L"Tour d'Observation",
	L"Depuis la Tour d'Eclaireur, vous \u00EAtes capable d'observer les terres \u00E9loign\u00E9es.",
	L"Depuis la Tour d'Observation, vous \u00EAtes capable d'observer les terres \u00E9loign\u00E9es. Tous vos H\u00E9ros re\u00E7oivent un bonus de +1 \u00E0 leurs points de d\u00E9placement.",
	L"Mine d'Or",
	L"Fosse \u00E0 Minerais",
	L"Scierie",
	L"Laboiratoire d'Alchimiste",
	L"Mine de Gemmes",
	L"Mine de Cristal",
	L"Mine de Soufre",
	L"Vous prenez contr\u00F4le d'une Mine d'Or. Elle vous fournira 1000 pi\u00E8ces d'or par jour.",
	L"Vous prenez contr\u00F4le d'une Fosse \u00E0 Minerais. Elle vous fournira deux unit\u00E9s de Minerais par jour.",
	L"Vous prenez contr\u00F4le d'une Scierie. Elle vous fournira deux unit\u00E9s de Bois par jour.",
	L"Vous prenez contr\u00F4le d'un Laboratoire d'Alchimiste. Il vous fournira une unit\u00E9 de Mercure par jour.",
	L"Vous prenez contr\u00F4le d'une Mine de Gemmes. Elle vous fournira une unit\u00E9 de Gemmes par jour.",
	L"Vous prenez contr\u00F4le d'une Mine de Cristal. Elle vous fournira une unit\u00E9 de Cristal par jour.",
	L"Vous prenez contr\u00F4le d'une Mine de Soufre. Elle vous fournira une unit\u00E9 de Soufre par jour.",
	L"Portes de la Ville",
	L"visit\u00E9",
	L"non visit\u00E9",
	L"Chevalier",
	L"Barbare",
	L"Magicien",
	L"Sorcier",
	L"Sorci\u00E8re",
	L"N\u00E9cromancien",
	L"Gerald",
	L"Fineous",
	L"Jacob",
	L"Schultz",
	L"Cantor",
	L"Bez",
	L"Earoon",
	L"Hedric",
	L"Tyrex",
	L"Grottekvarnen",
	L"Yog",
	L"Jaclyn",
	L"Krag",
	L"Baraka",
	L"Hapax",
	L"Krull",
	L"Cronus",
	L"Iona",
	L"Bernhard",
	L"Posid",
	L"Malcom",
	L"Morgana",
	L"Victor",
	L"Visarus",
	L"Gallatin",
	L"Altus",
	L"Odin",
	L"Kastore",
	L"Alamar",
	L"Eldor",
	L"Fondo",
	L"Marcus",
	L"Jack",
	L"Ferentona",
	L"Gem",
	L"Arven",
	L"Samira",
	L"Myrini",
	L"Rebecca",
	L"Dvergar",
	L"Rait",
	L"Urof",
	L"Tamika",
	L"Shra",
	L"Ruthven",
	L"Ranloo",
	L"Sandru",
	L"Knecht Ruprecth",
	L"Al\u00E9atoire",
	L"Citadelle",
	L"Bastion",
	L"Tour",
	L"Dongeon",
	L"Forteresse",
	L"N\u00E9cropole",
	L"Petit",
	L"Moyen",
	L"Grand",
	L"Huttes de Paysans",
	L"Tour des Archers",
	L"Salle de Garde",
	L"Barraquements",
	L"Ar\u00E8ne de Joutes",
	L"Cath\u00E9drale",
	L"Barraquement des Goblins",
	L"Tour des Orcs",
	L"Tani\u00E8re des Loups",
	L"Fort des Ogres",
	L"Pont des Trolls",
	L"Caverne des Cyclopes",
	L"Hutte des Hobbits",
	L"Bauge des Sangliers",
	L"Facture des Golems",
	L"Nid du Pic",
	L"Tour des Mages",
	L"Ch\u00E2teau C\u00E9leste",
	L"Caverne des Centaures",
	L"Crypte",
	L"Tour des Griffons",
	L"Labyrinthe",
	L"Marais des Hydres",
	L"Caverne des Dragons",
	L"Maisons Arboricoles",
	L"Cottage des Nains",
	L"Demeure Elfique",
	L"Cercle de Pierres",
	L"Clairi\u00E8re des Licornes",
	L"Tour de Rubis",
	L"Excavations",
	L"Cimetierre",
	L"Pyramide",
	L"Manoir",
	L"Mausol\u00E9e",
	L"Laboratoire",
	L"Guilde des Mages 1",
	L"Guilde des Mages 2",
	L"Guilde des Mages 3",
	L"Guilde des Mages 4",
	L"Guilde des Mages 5",
	L"N\u0153ud Magique",
	L"Taverne",
	L"Place du March\u00E9",
	L"Conseil",
	L"Mairie",
	L"Mine de Minerai",
	L"Scierie",
	L"Laboratoire d'Alchimiste",
	L"Mine de Gemmes",
	L"Mine de Cristal",
	L"Mine de Soufre",
	L"Douves",
	L"Donjon",
	L"Tourelle Gauche",
	L"Tourelle Droite",
	L"Champ de Tir",
	L"Salle des Officiers",
	L"For\u00EAt de Ch\u00EAnes",
	L"Chute d'Eau",
	L"Guilde des Mineurs",
	L"Tombes Profan\u00E9es",
	L"Tour de Garde",
	L"Fortifications",
	L"Hall du Valhalla",
	L"Mur d'Adobe",
	L"Mur de la Connaissance",
	L"Biblioth\u00E8que",
	L"Autel",
	L"Tourbillon Magique",
	L"Salle du Tr\u00E9sor",
	L"Bassin Mystique",
	L"Amplificateur de N\u00E9cromancie",
	L"Voile des T\u00E9n\u00E8bres",
	L"Le %s permet de recruter des %s.",
	L"En visitant la Guilde des Mages, un H\u00E9ros peut apprendre les sorts qu'elle contient.",
	L"R\u00E9g\u00E9n\u00E8re un point de magie par jour pour tous les H\u00E9ros alli\u00E9s.",
	L"La Taverne vous permet de recruter des H\u00E9ros et augmente le moral des troupes d\u00E9fendant la ville.",
	L"sur la Place du March\u00E9, vous pouvez acheter et vendre des ressources (les taux en vigueur s'am\u00E9liorent avec chaque Place du March\u00E9 que vous poss\u00E9dez).",
	L"Le Conseil augmente les revenus de votre royaume de 500 pi\u00E8ces d'or par jour.",
	L"La Mairie augmente les revenus de votre royaume de 1500 pi\u00E8ces d'or par jour.",
	L"La mine de minerai vous rapporte +1 en minerai par jour.",
	L"La scierie vous rapporte +1 en bois par jour.",
	L"Le laboratoire d'Alchimiste vous rapporte +1 en mercure par jour.",
	L"La mine de gemmes vous rapporte +1 en gemmes par jour.",
	L"La mine de cristal vous rapporte +1 en cristal par jour.",
	L"La mine de soufre vous rapporte +1 en soufre par jour.",
	L"Les douves ralentissent les attaquants. Toute unit\u00E9 y mettant les pieds doit y finir son tour et se retrouve en situation plus vuln\u00E9rable en cas d'attaque.",
	L"Le Donjon apporte une puissance de feu suppl\u00E9mentaire dans la d\u00E9fense du ch\u00E2teau.",
	L"La Tourelle Gauche apporte une puissance de feu suppl\u00E9mentaire dans la d\u00E9fense du ch\u00E2teau.",
	L"La Tourelle Droite apporte une puissance de feu suppl\u00E9mentaire dans la d\u00E9fense du ch\u00E2teau.",
	L"Le %s augmente de %d par semaine la production de %d.",
	L"La Tour de Garde augmente la distance de visibilit\u00E9 autour du ch\u00E2teau, et tous vos H\u00E9ros re\u00E7oivent un bonus de +5 \u00E0 leurs points de d\u00E9placement.",
	L"Les Fortifications am\u00E9liorent la solidit\u00E9 des murs du ch\u00E2teau en cas de si\u00E8ge.",
	L"Le Hall du Valhalla augmente de +1 l'Attaque des H\u00E9ros de passage.",
	L"Le Mur de la Connaissance augmente de +1 la Connaissance des H\u00E9ros de passage.",
	L"La Biblioth\u00E8que change al\u00E9atoirement certains des sorts stock\u00E9s dans votre Guilde des Mages au d\u00E9but de chaque mois.",
	L"L'Autel augmente les revenus de votre royaume de 1000 pi\u00E8ces d'or par jour.",
	L"Le Tourbillon Magique double temporairement les points de magie des H\u00E9ros le visitant.",
	L"Au d\u00E9but de chaque semaine, la Salle du Tr\u00E9sor ajoute 10% d'int\u00E9r\u00EAts \u00E0 la quantit\u00E9 totale d'or que vous poss\u00E9dez.",
	L"Le Bassin Mystique produit une petite quantit\u00E9 al\u00E9atoire de ressources chaque semaine.",
	L"L'Amplificateur de N\u00E9cromancie augmente de 10% la comp\u00E9tence de N\u00E9cromancie de tous les H\u00E9ros que vous contr\u00F4lez (et qui poss\u00E8dent cette comp\u00E9tence).",
	L"Le Voile des T\u00E9n\u00E8bres couvre votre ville d'un brouillard permanent imp\u00E9n\u00E9trable aux yeux des autres joueurs.",
	L"Le Bassin n'a encore rien produit.",
	L"Cette semaine, le Bassin a produit : %s.",
	L"Ep\u00E9e d'Argent",
	L"Faucille de Paysan",
	L"Plastron de Chevalier",
	L"Bouclier du Dragon",
	L"Anneau du Moine",
	L"Broche Magique de la Sorci\u00E8re",
	L"Parchemin de Connaissance Mineur",
	L"Rouleau de Parchemin",
	L"Pendentif de Sagesse",
	L"M\u00E9daille d'Honneur",
	L"M\u00E9daille de Distinction",
	L"D\u00E9 de Chance",
	L"Tr\u00E8fle de Chance",
	L"Oiseau d'Argent de Chance",
	L"Arc Long",
	L"Anneau du N\u00E9cromancien",
	L"T\u00E9l\u00E9scope",
	L"Cape d'Air de Protection",
	L"Cape de Terre de Protection",
	L"Cape de Feu de Protection",
	L"Cape d'Eau de Protection",
	L"Bocal d'Energie Magique",
	L"Hache de Puissance",
	L"Casque de Guerrier",
	L"Bracelet de Magie du Lanceur",
	L"Parchemin d'Illumination",
	L"Casque \u00E0 Pointe",
	L"Anneau du Sage",
	L"Collier de Perles Blanches",
	L"Oiseau Dor\u00E9 de Chance",
	L"Charriot de Minerai Infini",
	L"Cord\u00E9e de Bois Infini",
	L"Anneau de Vie",
	L"Pendentif de Vie",
	L"Arc Long d'Elfe",
	L"Capuchon de Vampire",
	L"Bottes de Voyageur",
	L"Plume de Diplomate",
	L"Cape de R\u00E9sistance",
	L"Cape de Vivacit\u00E9",
	L"Ep\u00E9e Enchant\u00E9e",
	L"Armure de Puissance",
	L"Anneau de Puissance",
	L"Tome de Connaissance",
	L"Ep\u00E9e Large Ancienne",
	L"Bouclier de Nain",
	L"Bouclier de Paladin",
	L"B\u00E2ton de la Magie",
	L"Parchemin de Connaissance Majeur",
	L"Livre de Sagesse",
	L"Eclipse",
	L"Bracelet du Serpent",
	L"Collier de Perles Noires",
	L"Pendentif de la Connaissance Absolue",
	L"Anneau de Perp\u00E9tuit\u00E9",
	L"Arbal\u00E8te",
	L"Ep\u00E9e de N\u00E9cromancien",
	L"Bourse d'Or Infinie",
	L"Sac d'Or Infini",
	L"Amulette de Richesse",
	L"Fiole de Mercure Infinie",
	L"Poche de Gemmes Infinie",
	L"Anneau de Soufre",
	L"Rose de Cristal",
	L"Bottes de Nomade",
	L"Ep\u00E9e Longue",
	L"Bouclier de H\u00E9ros",
	L"Casque du Pr\u00E9curseur",
	L"Chapeau de Magicien",
	L"Destructeur d'Ep\u00E9e",
	L"Collier de Seigneur de Guerre",
	L"Sph\u00E8re de N\u00E9gation",
	L"Baton de Sorcier",
	L"Cha\u00EEnes de Guerre",
	L"Couronne du Conqu\u00E9rant",
	L"Hache de lancer",
	L"Bouclier de goblin",
	L"Pendentif du lanceur",
	L"Ep\u00E9e du damn\u00E9",
	L"Sph\u00E8re d'Air",
	L"Sph\u00E8re de Terre",
	L"Sph\u00E8re de Feu",
	L"Sph\u00E8re d'Eau",
	L"Masse en Fer",
	L"Masse en Op",
	L"Ep\u00E9e en Or",
	L"Bouclier en Or",
	L"Armure en Or",
	L"Crane en Or",
	L"Jambi\u00E8res en Fer",
	L"Jambi\u00E8res en Os",
	L"Ep\u00E9e des B\u00E2tards",
	L"Cercle de l'Air",
	L"Chapeau de Ranger",
	L"Armure en Cuir",
	L"Calotte de Gobelin",
	L"Collier en Os",
	L"Gouvernail de Nain",
	L"Gouvernail de Rider",
	L"Bouclier de l'Ogre",
	L"Fl\u00E8ches",
	L"Baguette Solaire",
	L"Marteau de Nain",
	L"Casque Ail\u00E9",
	L"Casque en Os",
	L"Armure en Os",
	L"Armure du Roi",
	L"Collier de Pierre Sanglante",
	L"Arbal\u00E8te rapide",
	L"Bottes de Marais",
	L"Amulette de Glace",
	L"Augmente votre Attaque de 1.",
	L"Augmente votre Attaque de 1.",
	L"Augmente votre D\u00E9fense de 1.",
	L"Augmente votre D\u00E9fense de 1.",
	L"Augmente votre Magie de 1.",
	L"Augmente votre Magie de 1.",
	L"Augmente votre Connaissance de 1.",
	L"Augmente votre Connaissance de 1.",
	L"Augmente votre Connaissance de 1.",
	L"Augmente votre Moral de 1.",
	L"Augmente votre Moral de 1.",
	L"Augmente votre Chance de 1.",
	L"Augmente votre Chance de 1.",
	L"Augmente votre Chance de 1.",
	L"Augmente votre comp\u00E9tence d'Archer de 5%.",
	L"Augmente votre comp\u00E9tence de N\u00E9cromancie de 5%.",
	L"Permet \u00E0 votre h\u00E9ro de voir un carr\u00E9 de plus dans le brouillard.",
	L"R\u00E9duit de 30% les dommages caus\u00E9s par les sorts d'Air.",
	L"R\u00E9duit de 30% les dommages caus\u00E9s par les sorts de Terre.",
	L"R\u00E9duit de 30% les dommages caus\u00E9s par les sorts de Feu.",
	L"R\u00E9duit de 30% les dommages caus\u00E9s par les sorts d'Eau.",
	L"Permet de r\u00E9cup\u00E9rer 2 points de magie en plus par jour.",
	L"Augmente votre Attaque de 2.",
	L"Augmente votre D\u00E9fense de 2.",
	L"Augmente votre Magie de 2.",
	L"Augmente votre Connaissance de 2.",
	L"Augmente votre Attaque et votre D\u00E9fense de 1.",
	L"Augmente votre Magie et votre Connaissance de 1.",
	L"Augmente votre Magie et votre Connaissance de 1.",
	L"Augmente votre Chance de 2.",
	L"Vous fournit un +1 en Minerais par jour.",
	L"Vous fournit un +1 en Bois par jour.",
	L"Augmente la vie de vos unit\u00E9s de 1.",
	L"Augmente la vie de vos unit\u00E9s de 2.",
	L"Augmente votre comp\u00E9tence d'Archer de 10%.",
	L"Augmente votre comp\u00E9tence de N\u00E9cromancie de 10%.",
	L"Augmente votre mouvement sur terre de 20 points.",
	L"R\u00E9duit le co\u00FBt de se rendre de 20%",
	L"Augmente votre R\u00E9sistance \u00E0 la Magie de 10%",
	L"Augmente la vitesse de combat de toutes vos unit\u00E9s de 1.",
	L"Augmente votre Attaque de 3.",
	L"Augmente votre D\u00E9fense de 3.",
	L"Augmente votre Magie de 3.",
	L"Augmente votre Connaissance de 3.",
	L"Augmente votre Attaque de 4.",
	L"Augmente votre D\u00E9fense de 4.",
	L"Augmente votre D\u00E9fense de 4.",
	L"Augmente votre Magie de 4.",
	L"Augmente votre Connaissance de 4.",
	L"Augmente votre Connaissance de 4.",
	L"Augmente votre Attaque et votre D\u00E9fense de 2.",
	L"Augmente votre Magie et votre Connaissance de 2.",
	L"Augmente votre Magie et votre Connaissance de 2.",
	L"Augmente votre Attaque, D\u00E9fense, Magie, et Connaissance de 1.",
	L"Augmente la vie de vos unit\u00E9s de 3.",
	L"Augmente votre comp\u00E9tence d'Archer de 15%.",
	L"Augmente votre comp\u00E9tence de N\u00E9cromancie de 15%.",
	L"Augmente vos revenus de 500 pi\u00E8ces d'or par jour.",
	L"Augmente vos revenus de 750 pi\u00E8ces d'or par jour.",
	L"Augmente vos revenus de 1000 pi\u00E8ces d'or par jour.",
	L"Vous fournit un +1 en Mercure par jour.",
	L"Vous fournit un +1 en Gemmes par jour.",
	L"Vous fournit un +1 en Souffre par jour.",
	L"Vous fournit un +1 en Crystal par jour.",
	L"Augmente votre mouvement sur terre de 30 points.",
	L"Augmente votre Attaque de 6.",
	L"Augmente votre D\u00E9fense de 6.",
	L"Augmente votre Magie de 6.",
	L"Augmente votre Connaissance de 6.",
	L"Augmente votre Attaque et votre D\u00E9fense de 3.",
	L"Augmente votre Magie et votre Connaissance de 3.",
	L"Augmente votre Attaque, D\u00E9fense, Magie, et Connaissance de 2.",
	L"Ni vous ni votre adversaire ne pouvez battre en retraite ou vous rendre en combat.",
	L"Emp\u00EAche tout sort en combat.",
	L"Chaque type de h\u00E9ros re\u00E7oit son bonus sp\u00E9cial\u2026",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente de +4 votre Attaque, D\u00E9fense, Magie, et Connaissance. Augmente vos points de mouvement sur terre de +10%. Augmente de +2 la vitesse de combat de vos unit\u00E9s.",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente votre Attaque, D\u00E9fense, Magie, et Connaissance de +4. Donne \u00E0 vos troupes une r\u00E9sistance \u00E0 la magie de 50%. Permet \u00E0 vos troupes de tirer \u00E0 travers n'importe quel obstacle ou \u00E0 n'importe quelle distance sans p\u00E9nalit\u00E9.",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente votre Attaque et D\u00E9fense de +4, votre Magie et Connaissance de +6. Augmente l'efficacit\u00E9 des sorts r\u00E9surrection et convoquation de 50%.",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente votre Attaque et D\u00E9fense de +4, votre Magie et Connaissance de +6. R\u00E9g\u00E9n\u00E8re tous vos points de magie chaque jour.",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente votre Attaque et D\u00E9fense de +4, votre Magie et Connaissance de +6. Augmente les dommages de tous les sorts destructifs de 50%",
	L"Augmente vos revenus de 5000 pi\u00E8ces d'or par jour. Augmente votre Attaque et D\u00E9fense de +4, votre Magie et Connaissance de +6. Augmente votre capacit\u00E9 de n\u00E9crommancie de 15%. Ressuscite les morts du champ de bataille en tant que Momies.",
	L"Augmente votre Attaque de 6.",
	L"Augmente votre D\u00E9fense de 4.",
	L"Augmente votre Magie de 2.",
	L"Prot\u00E8ge votre h\u00E9ros de tous les autres joueurs avec un voile.",
	L"Augmente vos comp\u00E9tences en magie de l'Air de 50%.",
	L"Augmente vos comp\u00E9tences en magie de Terre de 50%.",
	L"Augmente vos comp\u00E9tences en magie de Feu de 50%.",
	L"Augmente vos comp\u00E9tences en magie de l'Eau de 50%.",
	L"Augmente votre Attaque de 1.",
	L"Augmente vos revenus de 250 pi\u00E8ces d'or par jour. Augmente votre Attaque de 3.",
	L"Augmente vos revenus de 250 pi\u00E8ces d'or par jour. Augmente votre Attaque de 3.",
	L"Augmente vos revenus de 250 pi\u00E8ces d'or par jour. Augmente votre D\u00E9fense de 3.",
	L"Augmente vos revenus de 250 pi\u00E8ces d'or par jour. Augmente votre D\u00E9fense de 2. Augmente votre Chance de 1.",
	L"Augmente votre Magie de 1.",
	L"Augmente votre D\u00E9fense de 2.",
	L"Augmente votre D\u00E9fense de 1.",
	L"Permet de r\u00E9cup\u00E9rer 5 points de magie en plus par jour.",
	L"Augmente votre Attaque de 2.",
	L"Augmente votre Magie de 1.",
	L"Augmente votre comp\u00E9tence d'Archer de 15%, Augmente la D\u00E9fense des Archers de 3.",
	L"Augmente votre D\u00E9fense de 1.",
	L"Augmente votre D\u00E9fense de 1, augmente la D\u00E9fense des Gobelins de 2.",
	L"Augmente votre Moral et votre Chance de 1.",
	L"Augmente votre D\u00E9fense de 2, augmente la D\u00E9fense des Nains de 4.",
	L"Augmente votre D\u00E9fense de 2.",
	L"Augmente votre D\u00E9fense de 2, augmente la D\u00E9fense des Ogres de 4.",
	L"Tirs illimit\u00E9s des unit\u00E9s attaquant \u00E0 distance.",
	L"Augmente votre Attaque de 3, augmente l'Attaque des Nains de 3.",
	L"Augmente votre D\u00E9fense de 2 et points de d\u00E9placement de 15.",
	L"Augmente votre D\u00E9fense de 2 et diminue le Moral ennemi de 2.",
	L"Augmente votre D\u00E9fense de 3 et diminue le Moral ennemi de 1.",
	L"Augmente votre D\u00E9fense de 3 et votre Moral de 1.",
	L"Augmente votre Magie de 1 et ajoute 15% d\u00E9g\u00E2ts de vos sorts.",
	L"Pas de p\u00E9nalit\u00E9 de distance pour les attaques \u00E0 distance.",
	L"Augmente vos d\u00E9placements sur terre de 25 points.",
	L"Diminue la vitesse des troupes ennemies de 2.",
	L"Quelques",
	L"Plusieurs",
	L"Groupe",
	L"Beaucoup",
	L"Horde",
	L"Foule",
	L"Essaim",
	L"L\u00E9gion",
	L"Quelques",
	L"Plusieurs",
	L"un groupe de",
	L"Beaucoup de",
	L"une horde de",
	L"une foule de",
	L"un essaim de",
	L"une l\u00E9gion de",
	L"Paysan",
	L"Paysans",
	L"Paysans",
	L"Archer",
	L"Archers",
	L"Archers",
	L"Lancier",
	L"Lanciers",
	L"Lanciers",
	L"Porte-\u00C9p\u00E9e",
	L"Porte-\u00C9p\u00E9es",
	L"Porte-\u00C9p\u00E9es",
	L"Chevalier",
	L"Chevaliers",
	L"Chevaliers",
	L"Paladin",
	L"Paladins",
	L"Paladins",
	L"Goblin",
	L"Goblins",
	L"Goblins",
	L"Orc",
	L"Orcs",
	L"Orcs",
	L"Monteur de loup",
	L"Monteurs de loup",
	L"Monteurs de loup",
	L"Ogre",
	L"Ogres",
	L"Ogres",
	L"Troll",
	L"Trolls",
	L"Trolls",
	L"Cyclope",
	L"Cyclopes",
	L"Cyclopes",
	L"Jeune Mage",
	L"Jeunes Mages",
	L"Jeunes Mages",
	L"Loup Blanc",
	L"Loups Blancs",
	L"Loups Blancs",
	L"Armure Vivante",
	L"Armures Vivantes",
	L"Armures Vivantes",
	L"P\u00E9gase",
	L"P\u00E9gases",
	L"P\u00E9gases",
	L"Mage",
	L"Mages",
	L"Mages",
	L"Thor",
	L"Thors",
	L"Thors",
	L"Centaure",
	L"Centaures",
	L"Centaures",
	L"Gargouille",
	L"Gargouilles",
	L"Gargouilles",
	L"Griffon",
	L"Griffons",
	L"Griffons",
	L"Minotaure",
	L"Minotaures",
	L"Minotaures",
	L"Hydre",
	L"Hydres",
	L"Hydres",
	L"Dragon Rouge",
	L"Dragons Rouges",
	L"Dragons Rouges",
	L"F\u00E9e",
	L"F\u00E9es",
	L"F\u00E9es",
	L"Nain",
	L"Nains",
	L"Nains",
	L"Elf",
	L"Elfs",
	L"Elfs",
	L"Druide",
	L"Druides",
	L"Druides",
	L"Licorne",
	L"Licornes",
	L"Licornes",
	L"Phoenix",
	L"Phoenix",
	L"Phoenix",
	L"Squelette",
	L"Squelettes",
	L"Squelettes",
	L"Zombie",
	L"Zombies",
	L"Zombies",
	L"Liche",
	L"Liches",
	L"Liches",
	L"Vampire",
	L"Vampires",
	L"Vampires",
	L"Chevalier Noir",
	L"Chevaliers Noirs",
	L"Chevaliers Noirs",
	L"Peste",
	L"Pestes",
	L"Pestes",
	L"Rodeur",
	L"Rodeurs",
	L"Rodeurs",
	L"Nomade",
	L"Nomades",
	L"Nomades",
	L"Spectre",
	L"Spectres",
	L"Spectres",
	L"Genie",
	L"Genies",
	L"Genies",
	L"M\u00E9duse",
	L"M\u00E9duses",
	L"M\u00E9duses",
	L"El\u00E9mentaire de Terre",
	L"El\u00E9mentaires de Terre",
	L"El\u00E9mentaires de Terre",
	L"El\u00E9mentaire d'Air",
	L"El\u00E9mentaires d'Air",
	L"El\u00E9mentaires d'Air",
	L"El\u00E9mentaire de Feu",
	L"El\u00E9mentaires de Feu",
	L"El\u00E9mentaires de Feu",
	L"El\u00E9mentaire d'Eau",
	L"El\u00E9mentaires d'Eau",
	L"El\u00E9mentaires d'Eau",
	L"Douves",
	L"Mur",
	L"Tourelle",
	L"Pont",
	L"Catapulte",
	L"Tire deux fois pour chaque attaque \u00E0 distance",
	L"Frappe deux fois par attaque",
	L"Ne subit pas de p\u00E9nalit\u00E9s lors de combat en corps-\u00E0-corps",
	L"Pas de riposte ennemie",
	L"Peur riposter \u00E0 un nombre illimit\u00E9 d'attaques",
	L"Attaque \u00E0 deux hex",
	L"Attaque toutes les troupes ennemies adjacentes",
	L"Attaque \u00E0 distance \u00E0 l'aide d'un nuage de mort qui cause des d\u00E9g\u00E2ts \u00E0 la cible, ainsi qu'\u00E0 toutes les cr\u00E9atures non Mort-Vivantes adjacentes",
	L"Cr\u00E9ature Mort-Vivante",
	L"Cr\u00E9ature Non-Vivante",
	L"R\u00E9g\u00E9n\u00E8re des points de vie \u00E0 chaque tour",
	L"Inflige des dommages suppl\u00E9mentaires (+5% par hex travers\u00E9 vers la cr\u00E9ature attaqu\u00E9e) lorqu'il charge en bataille",
	L"Immunis\u00E9 aux sorts de magie d'Air",
	L"Immunis\u00E9 aux sorts de magie de Terre",
	L"Immunis\u00E9 aux sorts de magie de Feu",
	L"Immunis\u00E9 aux sorts de magie d'Eau",
	L"A 40% de r\u00E9sistance \u00E0 la magie qui leurs donne une chance d'ignorer les effets d'une attaque magique",
	L"Ne re\u00E7oit que 25% des dommages de sorts",
	L"Les unit\u00E9s tu\u00E9es deviennent des Spectres",
	L"A 10% de chance de d\u00E9truire la moiti\u00E9 du groupe cibl\u00E9",
	L"Ressuscite les membres de leur propre groupe en regagnant un montant de vie \u00E9gal au montant des dommages inflig\u00E9s aux autres",
	L"Castellatus",
	L"Starkmauer",
	L"Kanan",
	L"Linderhoff",
	L"Whitemoon",
	L"Yaroslavl",
	L"Middleheim",
	L"Brettonia",
	L"Alexandretta",
	L"Whitestone",
	L"Claxton",
	L"Armitage",
	L"Shinnon",
	L"Gateway",
	L"Dunwall",
	L"Kildare",
	L"Kragg",
	L"Jimstadt",
	L"Hartgrim",
	L"Sandflash",
	L"Morganheim",
	L"Cragmoor",
	L"Dragonspire",
	L"Battlement",
	L"Bocc",
	L"Slau",
	L"Tormina",
	L"Dolere",
	L"Rockwarren",
	L"Strongglen",
	L"Kruber",
	L"Rovener",
	L"Tutanberg",
	L"Stronggale",
	L"Corona",
	L"Silverwing",
	L"Facture",
	L"Cloudfire",
	L"Cloudspire",
	L"Equinox",
	L"Athenaeum",
	L"Valtara",
	L"Tirith",
	L"Fallen Star",
	L"Mystos",
	L"Ayer",
	L"Silverspire",
	L"Manufactury",
	L"Veks",
	L"Sorrow Crown",
	L"Chillwater",
	L"Deepshadow",
	L"Darkhold",
	L"Blindroot",
	L"Shadowden",
	L"Scar",
	L"Malev",
	L"Castigare",
	L"Dukered",
	L"Shade",
	L"Evernight",
	L"Darkburrow",
	L"Lost Hold",
	L"Coldshadow",
	L"Starmino",
	L"Grigorov",
	L"Sigman",
	L"Still Water",
	L"Elfwind",
	L"Sebian",
	L"Ceiliedgh",
	L"Gladeroot",
	L"Avalon",
	L"Rainhaven",
	L"Strongglen",
	L"Marishen",
	L"Bath'iere",
	L"Green Falls",
	L"Emerald Moor",
	L"Wild Willow",
	L"Haunt's Wind",
	L"Cessacioun",
	L"Agony",
	L"Victorash",
	L"Terminus",
	L"Blackquarter",
	L"Sandro",
	L"Grave Raven",
	L"Dark Cloud",
	L"Coldsoul",
	L"Coldreign",
	L"Dark Eternal",
	L"Ghostwind",
	L"Blight",
	L"Shady Sands",
	L"Wolfengrott",
	L"Fl\u00E8che Magique",
	L"Protection contre la Terre",
	L"H\u00E2te",
	L"Bouclier",
	L"Rayon disloquant",
	L"Foudre",
	L"Pr\u00E9cision",
	L"Bouclier de l'Air",
	L"Mot Sacr\u00E9",
	L"Contre-Attaque",
	L"R\u00E9surrection",
	L"El\u00E9mentaire d'Air",
	L"Protection contre l'Air",
	L"Lenteur",
	L"Peau de Pierre",
	L"Visions",
	L"Tremblement de Terre",
	L"Lamentation",
	L"Pluie de M\u00E9t\u00E9ore",
	L"Portail magique",
	L"Implosion",
	L"El\u00E9mentaire de Terre",
	L"Soif de Sang",
	L"Protection contre l'Eau",
	L"Mal\u00E9diction",
	L"Aveuglement",
	L"Faiblesse",
	L"Vague de mort",
	L"Boule de Feu",
	L"Malchance",
	L"Animation des Morts",
	L"Explosion de Feu",
	L"Armageddon",
	L"El\u00E9mentaire de Feu",
	L"B\u00E9n\u00E9diction",
	L"Protection contre le Feu",
	L"Dissipation",
	L"Soin",
	L"Rayon gel\u00E9",
	L"Chance",
	L"Hilarit\u00E9",
	L"Anneau de Glace",
	L"Antie-Magie",
	L"Pri\u00E8re",
	L"El\u00E9mentaire d'Eau",
	L"Invocation de f\u00E9es",
	L"Un \u00E9clair d'\u00E9nergie magique frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*10).",
	L"Un \u00E9clair d'\u00E9nergie magique frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*10).",
	L"Un \u00E9clair d'\u00E9nergie magique frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*12).",
	L"Un \u00E9clair d'\u00E9nergie magique frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*15).",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de la Terre.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de la Terre.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts de la Terre.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts de la Terre.",
	L"Augmente de 3 la vitesse de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 3 la vitesse de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 5 la vitesse de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 5 la vitesse de toutes les unit\u00E9s alli\u00E9es.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 15% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques au corps \u00E0 corps.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 15% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques au corps \u00E0 corps.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques au corps \u00E0 corps.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 30% les d\u00E9g\u00E2ts qu'elles re\u00E7oivent d'attaques au corps \u00E0 corps.",
	L"R\u00E9duit de 3 la d\u00E9fense de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e. Un m\u00EAme ennemi peut \u00EAtre vis\u00E9 plusieurs fois par ce sort.",
	L"R\u00E9duit de 3 la d\u00E9fense de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e. Un m\u00EAme ennemi peut \u00EAtre vis\u00E9 plusieurs fois par ce sort.",
	L"R\u00E9duit de 4 la d\u00E9fense de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e. Un m\u00EAme ennemi peut \u00EAtre vis\u00E9 plusieurs fois par ce sort.",
	L"R\u00E9duit de 5 la d\u00E9fense de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e. Un m\u00EAme ennemi peut \u00EAtre vis\u00E9 plusieurs fois par ce sort.",
	L"Cr\u00E9e un \u00E9clair qui va frapper l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*25).",
	L"Cr\u00E9e un \u00E9clair qui va frapper l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*25).",
	L"Cr\u00E9e un \u00E9clair qui va frapper l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*27).",
	L"Cr\u00E9e un \u00E9clair qui va frapper l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*30).",
	L"Augmente de 3 les d\u00E9g\u00E2ts inflig\u00E9s par les attaques \u00E0 distance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 3 les d\u00E9g\u00E2ts inflig\u00E9s par les attaques \u00E0 distance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 5 les d\u00E9g\u00E2ts inflig\u00E9s par les attaques \u00E0 distance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 5 les d\u00E9g\u00E2ts inflig\u00E9s par les attaques \u00E0 distance de toutes les unit\u00E9s alli\u00E9es.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 25% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques \u00E0 distance.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 25% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques \u00E0 distance.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 50% les d\u00E9g\u00E2ts qu'elle re\u00E7oit d'attaques \u00E0 distance.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 50% les d\u00E9g\u00E2ts qu'elles re\u00E7oivent d'attaques \u00E0 distance.",
	L"Tente de d\u00E9truire toute cr\u00E9ature mort-vivante sur le champ de bataille (Magie*10).",
	L"Tente de d\u00E9truire toute cr\u00E9ature mort-vivante sur le champ de bataille (Magie*10).",
	L"Tente de d\u00E9truire toute cr\u00E9ature mort-vivante sur le champ de bataille (Magie*12).",
	L"Tente de d\u00E9truire toute cr\u00E9ature mort-vivante sur le champ de bataille (Magie*15).",
	L"L'unit\u00E9 s\u00E9lectionn\u00E9e pourra riposter une fois suppl\u00E9mentaires lors du prochain tour.",
	L"L'unit\u00E9 s\u00E9lectionn\u00E9e pourra riposter une fois suppl\u00E9mentaires lors du prochain tour.",
	L"L'unit\u00E9 s\u00E9lectionn\u00E9e pourra riposter deux fois suppl\u00E9mentaires lors du prochain tour.",
	L"L'unit\u00E9 s\u00E9lectionn\u00E9e pourra riposter trois fois suppl\u00E9mentaires lors du prochain tour.",
	L"Fait revenir \u00E0 la vie des unit\u00E9s du groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*40).",
	L"Fait revenir \u00E0 la vie des unit\u00E9s du groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*40).",
	L"Fait revenir \u00E0 la vie des unit\u00E9s du groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*45).",
	L"Fait revenir \u00E0 la vie des unit\u00E9s du groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*50).",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Air (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Air (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Air (Magie*4). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Air (Magie*5). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de l'Air.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de l'Air.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts de l'Air.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts de l'Air.",
	L"R\u00E9duit de 3 la vitesse de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 3 la vitesse de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 6 la vitesse de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 6 la vitesse de toutes les unit\u00E9s ennemies.",
	L"Augmente de 3 la comp\u00E9tence de d\u00E9fense de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 3 la comp\u00E9tence de d\u00E9fense de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 6 la comp\u00E9tence de d\u00E9fense de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 6 la comp\u00E9tence de d\u00E9fense de toutes les unit\u00E9s alli\u00E9es.",
	L"Vous donne le nombre exact de cr\u00E9atures errantes et pr\u00E9cise si elles sont pr\u00EAtes \u00E0 rejoindre votre H\u00E9ros. Vous permet de conna\u00EEtre les comp\u00E9tences principales, ainsi que le type et la quantit\u00E9 de cr\u00E9atures d'un H\u00E9ros ennemi proche, comme s'il faisait partie de votre Royaume. Fonctionne de la m\u00EAme fa\u00E7on pour les villes ennemies proches (statistiques, cr\u00E9atures en garnison).",
	L"Vous donne le nombre exact de cr\u00E9atures errantes et pr\u00E9cise si elles sont pr\u00EAts \u00E0 rejoindre votre H\u00E9ros. Vous permet de conna\u00EEtre les comp\u00E9tences principales, ainsi que le type et la quantit\u00E9 de cr\u00E9atures d'un H\u00E9ros ennemi proche, comme s'il faisait partie de votre Royaume. Fonctionne de la m\u00EAme fa\u00E7on pour les villes ennemies proches (statistiques, cr\u00E9atures en garnison).",
	L"Vous donne le nombre exact de cr\u00E9atures errantes et pr\u00E9cise si elles sont pr\u00EAts \u00E0 rejoindre votre H\u00E9ros. Vous permet de conna\u00EEtre les comp\u00E9tences principales, ainsi que le type et la quantit\u00E9 de cr\u00E9atures d'un H\u00E9ros ennemi proche, comme s'il faisait partie de votre Royaume. Fonctionne de la m\u00EAme fa\u00E7on pour les villes ennemies proches (statistiques, cr\u00E9atures en garnison).",
	L"Vous donne le nombre exact de cr\u00E9atures errantes et pr\u00E9cise si elles sont pr\u00EAts \u00E0 rejoindre votre H\u00E9ros. Vous permet de conna\u00EEtre les comp\u00E9tences principales, ainsi que le type et la quantit\u00E9 de cr\u00E9atures d'un H\u00E9ros ennemi proche, comme s'il faisait partie de votre Royaume. Fonctionne de la m\u00EAme fa\u00E7on pour les villes ennemies proches (statistiques, cr\u00E9atures en garnison).",
	L"Endommage al\u00E9atoirement deux sections d'un rempart en combat.",
	L"Endommage al\u00E9atoirement deux sections d'un rempart en combat.",
	L"Endommage al\u00E9atoirement trois sections d'un rempart en combat.",
	L"Endommage al\u00E9atoirement quatre sections d'un rempart en combat.",
	L"R\u00E9duit de 1 le moral de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 1 le moral de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 2 le moral de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 2 le moral de toutes les unit\u00E9s ennemies.",
	L"Une pluie de m\u00E9t\u00E9ores s'abat sur la cible ainsi que sur les unit\u00E9s adjacentes (Magie*25).",
	L"Une pluie de m\u00E9t\u00E9ores s'abat sur la cible ainsi que sur les unit\u00E9s adjacentes (Magie*25).",
	L"Une pluie de m\u00E9t\u00E9ores s'abat sur la cible ainsi que sur les unit\u00E9s adjacentes (Magie*27).",
	L"Une pluie de m\u00E9t\u00E9ores s'abat sur la cible ainsi que sur les unit\u00E9s adjacentes (Magie*30).",
	L"Tel\u00E9porte votre H\u00E9ros vers la ville alli\u00E9e la plus proche. Cette ville doit \u00EAtre inoccup\u00E9e.",
	L"Tel\u00E9porte votre H\u00E9ros vers la ville alli\u00E9e la plus proche. Cette ville doit \u00EAtre inoccup\u00E9e.",
	L"Tel\u00E9porte votre H\u00E9ros vers n'importe quelle ville alli\u00E9e inoccup\u00E9e.",
	L"Tel\u00E9porte votre H\u00E9ros vers n'importe quelle ville alli\u00E9e inoccup\u00E9e.",
	L"Inflige des d\u00E9g\u00E2ts massifs \u00E0 l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*70).",
	L"Inflige des d\u00E9g\u00E2ts massifs \u00E0 l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*70).",
	L"Inflige des d\u00E9g\u00E2ts massifs \u00E0 l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*75).",
	L"Inflige des d\u00E9g\u00E2ts massifs \u00E0 l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*80).",
	L"Vous permet d'invoquer des El\u00E9mentaires de Terre (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Terre (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Terre (Magie*4). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Terre (Magie*5). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Augmente de 3 les d\u00E9g\u00E2ts au corps \u00E0 corps inflig\u00E9s par l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 3 les d\u00E9g\u00E2ts au corps \u00E0 corps inflig\u00E9s par l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 6 les d\u00E9g\u00E2ts au corps \u00E0 corps inflig\u00E9s par l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 6 les d\u00E9g\u00E2ts au corps \u00E0 corps inflig\u00E9s par toutes les unit\u00E9s alli\u00E9es.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de l'Eau.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts de l'Eau.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e, r\u00E9duisant de 60% tous les d\u00E9g\u00E2ts provenant de sorts de l'Eau.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 60% tous les d\u00E9g\u00E2ts provenant de sorts de l'Eau.",
	L"L'unit\u00E9 ennemie s\u00E9lectionn\u00E9e inflige le minimum de d\u00E9g\u00E2ts au combat.",
	L"L'unit\u00E9 ennemie s\u00E9lectionn\u00E9e inflige le minimum de d\u00E9g\u00E2ts au combat.",
	L"L'unit\u00E9 ennemie s\u00E9lectionn\u00E9e inflige le minimum de d\u00E9g\u00E2ts au combat.",
	L"Toutes les unit\u00E9s ennemies infligent le minimum de d\u00E9g\u00E2ts au combat.",
	L"Aveugle une cr\u00E9ature qui se retrouve dans l'impossibilit\u00E9 de bouger et qui ne peut contre-attaquer qu'avec une force divis\u00E9e de 2. L'aveuglement perdure jusqu'\u00E0 ce que la cr\u00E9ature soit attaqu\u00E9e ou que le sort soit dissip\u00E9.",
	L"Aveugle une cr\u00E9ature qui se retrouve dans l'impossibilit\u00E9 de bouger et qui ne peut contre-attaquer qu'avec une force divis\u00E9e de 2. L'aveuglement perdure jusqu'\u00E0 ce que la cr\u00E9ature soit attaqu\u00E9e ou que le sort soit dissip\u00E9.",
	L"Aveugle une cr\u00E9ature qui se retrouve dans l'impossibilit\u00E9 de bouger et qui ne peut contre-attaquer qu'avec une force divis\u00E9e de 4. L'aveuglement perdure jusqu'\u00E0 ce que la cr\u00E9ature soit attaqu\u00E9e ou que le sort soit dissip\u00E9.",
	L"Aveugle une cr\u00E9ature qui se retrouve dans l'impossibilit\u00E9 de bouger ou de contre-attaquer. L'aveuglement perdure jusqu'\u00E0 ce que la cr\u00E9ature soit attaqu\u00E9e ou que le sort soit dissip\u00E9.",
	L"R\u00E9duit de 3 la comp\u00E9tence d'attaque de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 3 la comp\u00E9tence d'attaque de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 6 la comp\u00E9tence d'attaque de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 6 la comp\u00E9tence d'attaque de toutes les unit\u00E9s ennemies.",
	L"Envoie une vague de mort \u00E0 travers le champ de bataille, infligeant des points de d\u00E9g\u00E2ts \u00E0 toutes les unit\u00E9s non mort-vivantes (Magie*5).",
	L"Envoie une vague de mort \u00E0 travers le champ de bataille, infligeant des points de d\u00E9g\u00E2ts \u00E0 toutes les unit\u00E9s non mort-vivantes (Magie*5).",
	L"Envoie une vague de mort \u00E0 travers le champ de bataille, infligeant des points de d\u00E9g\u00E2ts \u00E0 toutes les unit\u00E9s non mort-vivantes (Magie*7).",
	L"Envoie une vague de mort \u00E0 travers le champ de bataille, infligeant des points de d\u00E9g\u00E2ts \u00E0 toutes les unit\u00E9s non mort-vivantes (Magie*10).",
	L"La cible s\u00E9lectionn\u00E9e entre soudain en combustion, subissant des d\u00E9g\u00E2ts de feu qui touchent \u00E9galement les unit\u00E9s adjacentes (Magie*15).",
	L"La cible s\u00E9lectionn\u00E9e entre soudain en combustion, subissant des d\u00E9g\u00E2ts de feu qui touchent \u00E9galement les unit\u00E9s adjacentes (Magie*15).",
	L"La cible s\u00E9lectionn\u00E9e entre soudain en combustion, subissant des d\u00E9g\u00E2ts de feu qui touchent \u00E9galement les unit\u00E9s adjacentes (Magie*17).",
	L"La cible s\u00E9lectionn\u00E9e entre soudain en combustion, subissant des d\u00E9g\u00E2ts de feu qui touchent \u00E9galement les unit\u00E9s adjacentes (Magie*20).",
	L"R\u00E9duit de 1 la chance de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 1 la chance de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 2 la chance de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e.",
	L"R\u00E9duit de 2 la chance de toutes les unit\u00E9s ennemies.",
	L"R\u00E9anime des morts-vivants tu\u00E9s dans le groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*40).",
	L"R\u00E9anime des morts-vivants tu\u00E9s dans le groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*40).",
	L"R\u00E9anime des morts-vivants tu\u00E9s dans le groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*45).",
	L"R\u00E9anime des morts-vivants tu\u00E9s dans le groupe s\u00E9lectionn\u00E9 en redonnant un certain nombre de points de vie \u00E0 ce dernier (Magie*50).",
	L"Une grosse explosion de feu frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*15). Eviter de vous trouver trop pr\u00E8s \u00E0 ce moment l\u00E0!",
	L"Une grosse explosion de feu frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*15). Eviter de vous trouver trop pr\u00E8s \u00E0 ce moment l\u00E0!",
	L"Une grosse explosion de feu frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*17). Eviter de vous trouver trop pr\u00E8s \u00E0 ce moment l\u00E0!",
	L"Une grosse explosion de feu frappe l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*20). Eviter de vous trouver trop pr\u00E8s \u00E0 ce moment l\u00E0!",
	L"Une pluie de feu s'abat sur le champ de bataille, blessant toutes les unit\u00E9s (Magie*40).",
	L"Une pluie de feu s'abat sur le champ de bataille, blessant toutes les unit\u00E9s (Magie*40).",
	L"Une pluie de feu s'abat sur le champ de bataille, blessant toutes les unit\u00E9s (Magie*45).",
	L"Une pluie de feu s'abat sur le champ de bataille, blessant toutes les unit\u00E9s (Magie*50).",
	L"Vous permet d'invoquer des El\u00E9mentaires de Feu (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Feu (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Feu (Magie*4). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires de Feu (Magie*5). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Permet \u00E0 l'unit\u00E9 alli\u00E9e s\u00E9lectionn\u00E9e d'infliger le maximum de d\u00E9g\u00E2ts au combat.",
	L"Permet \u00E0 l'unit\u00E9 alli\u00E9e s\u00E9lectionn\u00E9e d'infliger le maximum de d\u00E9g\u00E2ts au combat.",
	L"Permet \u00E0 l'unit\u00E9 alli\u00E9e s\u00E9lectionn\u00E9e d'infliger le maximum de d\u00E9g\u00E2ts au combat.",
	L"Permet \u00E0 toutes les unit\u00E9s alli\u00E9es d'infliger le maximum de d\u00E9g\u00E2ts au combat.",
	L"Prot\u00E8ge l'unit\u00E9s alli\u00E9e s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts du Feu.",
	L"Prot\u00E8ge l'unit\u00E9s alli\u00E9e s\u00E9lectionn\u00E9e, r\u00E9duisant de 30% tous les d\u00E9g\u00E2ts provenant de sorts du Feu.",
	L"Prot\u00E8ge l'unit\u00E9s alli\u00E9e s\u00E9lectionn\u00E9e, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts du Feu.",
	L"Prot\u00E8ge toutes les unit\u00E9s alli\u00E9es, r\u00E9duisant de 50% tous les d\u00E9g\u00E2ts provenant de sorts du Feu.",
	L"Supprime tous les effets magiques affectant l'unit\u00E9 alli\u00E9e s\u00E9lectionn\u00E9e.",
	L"Supprime tous les effets magiques affectant l'unit\u00E9 alli\u00E9e s\u00E9lectionn\u00E9e.",
	L"Supprime tous les effets magiques affectant l'unit\u00E9 alli\u00E9e ou ennemie s\u00E9lectionn\u00E9e.",
	L"Supprime tous les effets magiques de toutes les cr\u00E9atures sur le champ de bataille.",
	L"Supprime tous les effets magiques n\u00E9gatifs et soigne un petit nombre de points de vie de l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*5)",
	L"Supprime tous les effets magiques n\u00E9gatifs et soigne un petit nombre de points de vie de l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*5)",
	L"Supprime tous les effets magiques n\u00E9gatifs et soigne un petit nombre de points de vie de l'unit\u00E9 s\u00E9lectionn\u00E9e (Magie*7)",
	L"Supprime tous les effets magiques n\u00E9gatifs et soigne un petit nombre de points de vie de toutes les unit\u00E9s alli\u00E9es (Magie*7)",
	L"Draine la chaleur corporelle de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*20).",
	L"Draine la chaleur corporelle de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*20).",
	L"Draine la chaleur corporelle de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*22).",
	L"Draine la chaleur corporelle de l'unit\u00E9 ennemie s\u00E9lectionn\u00E9e (Magie*25).",
	L"Augmente de 1 la chance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 1 la chance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 2 la chance de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 2 la chance de toutes les unit\u00E9s alli\u00E9es.",
	L"Augmente de 1 le moral de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 1 le moral de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 2 le moral de l'unit\u00E9 s\u00E9lectionn\u00E9e.",
	L"Augmente de 2 le moral de toutes les unit\u00E9s alli\u00E9es.",
	L"Draine la chaleur corporelle de toutes les unit\u00E9s adjacentes \u00E0 la cible, sans infliger de d\u00E9g\u00E2ts \u00E0 cette derni\u00E8re (Magie*10).",
	L"Draine la chaleur corporelle de toutes les unit\u00E9s adjacentes \u00E0 la cible, sans infliger de d\u00E9g\u00E2ts \u00E0 cette derni\u00E8re (Magie*10).",
	L"Draine la chaleur corporelle de toutes les unit\u00E9s adjacentes \u00E0 la cible, sans infliger de d\u00E9g\u00E2ts \u00E0 cette derni\u00E8re (Magie*12).",
	L"Draine la chaleur corporelle de toutes les unit\u00E9s adjacentes \u00E0 la cible, sans infliger de d\u00E9g\u00E2ts \u00E0 cette derni\u00E8re (Magie*15).",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e contre tous les sorts de niveau 1 \u00E0 3.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e contre tous les sorts de niveau 1 \u00E0 3.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e contre tous les sorts de niveau 1 \u00E0 4.",
	L"Prot\u00E8ge l'unit\u00E9 s\u00E9lectionn\u00E9e contre tous les sorts.",
	L"Ajoute un bonus de 2 aux comp\u00E9tences d'attaque, de d\u00E9fense et de vitesse de toutes les unit\u00E9s alli\u00E9es.",
	L"Ajoute un bonus de 2 aux comp\u00E9tences d'attaque, de d\u00E9fense et de vitesse de toutes les unit\u00E9s alli\u00E9es.",
	L"Ajoute un bonus de 4 aux comp\u00E9tences d'attaque, de d\u00E9fense et de vitesse de toutes les unit\u00E9s alli\u00E9es.",
	L"Ajoute un bonus de 4 aux comp\u00E9tences d'attaque, de d\u00E9fense et de vitesse de toutes les unit\u00E9s alli\u00E9es.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Eau (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Eau (Magie*3). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Eau (Magie*4). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des El\u00E9mentaires d'Eau (Magie*5). Une fois ce sort lanc\u00E9, aucun autre type d'\u00E9l\u00E9mentaire ne peut \u00EAtre invoqu\u00E9.",
	L"Vous permet d'invoquer des F\u00E9es (Magie*5).",
	L"Vous permet d'invoquer des F\u00E9es (Magie*5).",
	L"Vous permet d'invoquer des F\u00E9es (Magie*7).",
	L"Vous permet d'invoquer des F\u00E9es (Magie*10).",
	L"Apr\u00E8s un pourboire g\u00E9n\u00E9reux, le tenancier murmure:",
	L"Un homme sage a dit un jour, \"Ne partagez votre sagesse avec personne.\"",
	L"Le sang est plus \u00E9pais que l'eau.",
	L"Soyez honn\u00EAtes envers vous m\u00EAmes!",
	L"Trouvez le Graal - il est plus puissant que vous ne pouvez l'imaginer.",
	L"Lors des combats, prot\u00E9gez toujours vos unit\u00E9s d'attaque \u00E0 distance.",
	L"Parfois, la meilleure fa\u00E7on d'\u00E9viter la d\u00E9faite est d'\u00E9viter le combat.",
	L"Attaquez votre ennemi sur son point fable.",
	L"Avez-vous d\u00E9j\u00E0 entendu l'histoire de la grenouille qui r\u00EAvait de devenir roi\u2026 et qui a r\u00E9alis\u00E9 ce r\u00EAve?",
	L"Aujourd'hui est le lendemain d'hier.",
	L"Lorsque vous voyagez \u00E0 travers le d\u00E9sert, recherchez une oasis, elle acc\u00E9l\u00E8rera votre travers\u00E9e.",
	L"Il y a une s\u00E9curit\u00E9 dans le nombre, surtout si ce nombre se compte en milliers!",
	L"N'oubliez pas que le Dragon Noir est immunis\u00E9 contre tous les sorts.",
	L"Combattez le Feu avec une Protection contre le Feu.",
	L"Les Paladins sont les cr\u00E9atures les plus puissantes de la Citadelle.",
	L"Les Cyclopes sont les cr\u00E9atures les plus puissantes du Bastion.",
	L"Les Titans sont les cr\u00E9atures les plus puissantes de la Tour.",
	L"Les Dragons Noirs sont les cr\u00E9atures les plus puissantes du Dongeon.",
	L"Les Phoenix sont les cr\u00E9atures les plus puissantes de la Forteresse",
	L"Les Dragons d'Os sont les cr\u00E9atures les plus puissantes de la N\u00E9cropole.",
	L"Eh, je suis \u00E0 court de rumeurs, parce que les gens comme VOUS ne viennent pas suffisamment souvent les partager avec moi.",
	L"Laissez vos Cavaliers charger \u00E0 travers vos ennemis. Vous appr\u00E9cierez le r\u00E9sultat. Plus la distance est \u00E9lev\u00E9e, mieux c'est.",
	L"J'ai vu une fois un Nain r\u00E9sister \u00E0 un sort dirig\u00E9 contre lui.",
	L"Sur le champ de bataille, celui qui frappe en premier a le plus de chances de gagner.",
	L"Sur le champ de bataille, la vivacit\u00E9 sauve la vie.",
	L"J'ai vu des Vampires mourants rena\u00EEtre dans le sang des ennemis tomb\u00E9s au combat.",
	L"Il est impossible de riposter \u00E0 une terrifiante attaque de Vampire.",
	L"L'attaque d'une Liche transperce les vivants sans toucher les mort-vivants.",
	L"Sur le champ de bataille, les Dragon d'Os remplissent de terreur le c\u0153ur de leurs ennemis.",
	L"Les Golems n'ont pas de volont\u00E9 propre.",
	L"Les Golems sont anim\u00E9s par une magie qui reste inconnue de la plupart des hommes.",
	L"A cause de leur nature anim\u00E9e, les golems endurent la punition des sorts plus longtemps que les autres.",
	L"Les Titans frapperont les Dragons Noirs plus f\u00E9rocement que n'importe quel autre ennemi.",
	L"Beaucoup craignent le pouvoir p\u00E9trifiant de l'attaque d'une M\u00E9duse. Vous devriez plut\u00F4t craindre leurs fl\u00E8ches dor\u00E9es.",
	L"M\u00EAme contre l'insurmontable, les Minotaures se r\u00E9v\u00E8lent dans la folie sanguinaire du combat.",
	L"Aucun sort en ce bas monde ne peut blesser un Dragon Noir.",
	L"On raconte qu'au cours des combats, les Dragons Noirs recherchent d'abord les Titans.",
	L"Il est impossible de riposter \u00E0 l'assaut brutal des multiples t\u00EAtes d'une Hydre,",
	L"Certains pensent que chaque N\u00E9cropole construit un \"Amplificateur N\u00E9cromantique\" pour aider ses H\u00E9ros \u00E0 relever les morts.",
	L"Les h\u00E9ros visitant le Hall du Valhalla dans un Bastion deviennent de meilleurs guerriers.",
	L"Join",
	L"Create",
	L"Launch!",
	L"Ready",
	L"Profile...",
	L"Failure",
	L"Failed connecting. Please try again later",
	L"Player dropped",
	L"%s player dropped and was replaced with computer player.",
	L"Game dropped",
	L"Host decided to drop the game.",
	L"Unable to log in",
	L"User ID invalid.",
	L"You are participating in a game",
	L"Do you want to resume it?",
	L"Game doesn't exist anymore.",
	L"Game full.",
	L"Unable to join",
	L"Unable to create",
	L"Game you were participating in was terminated.",
	L"Uploading savegame...",
	L"Downloading savegame",
	L"Connecting to server...",
	L"Network unavailable",
	L"Players in lobby",
	L"Human player jumped in",
	L"Unable to launch game, please wait for more players to join.",
	L"%s player (AI) was replaced by human player %s.",
	L"Checking for updates...",
	L"Update available",
	L"Would you like to update now?",
	L"Updating...",
	L"The game will now restart to complete update process",
	L"",
	L"",
	L"",
	L""};
