/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

#include <stdafx.h>
#include "cnst_text.h" 

LPCWSTR LANG_DATA_GER[1665] = {
	L"",
	L"+",
	L"-",
	L"Ok",
	L"Abbruch",
	L"Ja",
	L"Nein",
	L"Neustart",
	L"n/a",
	L"Schliessen",
	L"Hilfe",
	L"Beschw\u00F6ren",
	L"Info",
	L"Kartengr\u00F6\u00DFe",
	L"Kartenversion",
	L"Autor",
	L"Entlassen",
	L"Bauen",
	L"Rekrutieren",
	L"Ben\u00F6tigt:",
	L"Kosten:",
	L"Wache:",
	L"Bereits Besucht",
	L"Nicht Besucht",
	L"Besitzer",
	L"Niemand",
	L"Teilen",
	L"Handeln",
	L"Kapitulieren",
	L"R\u00FCckzug",
	L"Laden",
	L"Speichern",
	L"<...>",
	L"Lade ein gespeichertes Spiel:",
	L"Speichere das aktuelle Spiel",
	L"W\u00E4hle das Spielszenario:",
	L"Sieg",
	L"Niederlage",
	L"Kartenname",
	L"Autokampf",
	L"\u00DCberblick K\u00F6nigreich",
	L"Kartenteile",
	L"System Men\u00FC",
	L"T\u00E4gliches Einkommen:",
	L"Unerforschtes Gebiet",
	L"Unbesetzt",
	L"Kein Gasthaus",
	L"Bestimmungsort w\u00E4hlen",
	L"Wachstum",
	L"Verf\u00FCgbar",
	L"Kosten pro Einheit",
	L"Rekrutieren",
	L"Gesamtkosten",
	L"Mana",
	L"Stufe",
	L"Lvl",
	L"Erfahrung",
	L"Reise Punkte",
	L"Wachen zur\u00FCcklassen",
	L"Speichern unter",
	L"Spiel Datum",
	L"Rohstoffe K\u00F6nigreich",
	L"Verf\u00FCgbar zum Handel",
	L"Auf einer Lichtung siehst du ein antikes Artefakt. Ungl\u00FCcklicherweise wird es bewacht von:",
	L"Best\u00FCrzt stellst du fest, das %s ist bewacht von:",
	L"Willst Du die Wachen bek\u00E4mpfen?",
	L"Registrierung",
	L"Ger\u00E4te ID:",
	L"Registrierungsschl\u00FCssel",
	L"Registrieren",
	L"Sp\u00E4ter",
	L"Registrierung erfolgreich",
	L"Registrierung fehlgeschlagen",
	L"Der angegebene Registrierungsschl\u00FCssel ist ung\u00FCltig.",
	L"Vielen Dank!",
	L"Besuche unsere offizielle Webseite www.pocketheroes.net um Pocket Heroes zu kaufen.",
	L"",
	L"Durch den Erwerb von Pocket Heroes von #FCCCN #FFF6Handango#FCCC bekommen Sie einen Registrierungsschl\u00FCssel. Bitte aktivieren Sie Ihre Kopie von Pocket Heroes unter: www.pocketheroes.org",
	L"Musik",
	L"Aus",
	L"Tasten",
	L"Spezielle Tastaturbelegung",
	L"Spiel Sprache",
	L"Dr\u00FCcken Sie die Taste, die Sie zuordnen wollen ...",
	L"- N/A -",
	L"Start",
	L"Hoch",
	L"Runter",
	L"Links",
	L"Rechts",
	L"Taste #1",
	L"Taste #2",
	L"Taste #3",
	L"Taste #4",
	L"Taste #5",
	L"Taste #6",
	L"Aufzeichnen",
	L"Sprechen",
	L"Ende",
	L"Zur\u00FCck",
	L"Men\u00FC",
	L"Soft #1",
	L"Soft #2",
	L"Hilfe Modus",
	L"Benutzerdefiniert",
	L"\u00DCbersichtskarte",
	L"Minimieren",
	L"Screenshot erstellen",
	L"Quicksave",
	L"Zeige die Heldenerinnerung",
	L"Raster auf Karte anzeigen",
	L"Raster im Kampf anzeigen",
	L"Schneller Kampf",
	L"Bewegungspunkte anzeigen",
	L"\u00DCbersichtskarte gl\u00E4tten",
	L"\u00DCbersichtskarte 4x verkleinen",
	L"Linksh\u00E4nder Modus",
	L"Autospeicher",
	L"Autozoom On Hold",
	L"Musik Lautst\u00E4rke",
	L"Gammawertanzeige",
	L"Karte scrollen",
	L"Laufgeschwindigkeit des Helden",
	L"Kampfgeschwindigkeit",
	L"Sehr Langsam",
	L"Langsam",
	L"Normal",
	L"Schnell",
	L"Sehr Schnell",
	L"Jan",
	L"Feb",
	L"M\u00E4r",
	L"Apr",
	L"Mai",
	L"Jun",
	L"Jul",
	L"Aug",
	L"Sep",
	L"Okt",
	L"Nov",
	L"Dez",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ein anderes Spiel laden m\u00F6chten?",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ein neues Szenario beginnen m\u00F6chten?",
	L"Sind Sie sicher das Sie das Spiel beenden m\u00F6chten?",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ins Hauptmen\u00FC wechseln m\u00F6chten?",
	L"Der ausgew\u00E4hlte Speicherplatz ist bereits in Verwendung. M\u00F6chten Sie ihn \u00DCberschreiben?",
	L"Spiel gespeichert...",
	L"Screenshot gespeichert...",
	L"Entschuldigung - Diese Funktion ist in der aktuellen Version nicht verf\u00FCgbar.",
	L"Sie haben gewonnen!",
	L"Hat Stufe %d erreicht",
	L"#FFFF%s #S0#FDDD(%s Stufe %d)",
	L"Alle Bedingungen f\u00FCr dieses Geb\u00E4ude sind erf\u00FCllt",
	L"Bereits gebaut",
	L"Sind Sie sicher, dass Sie diese Armee entlassen m\u00F6chten?",
	L"Sind Sie sicher, dass Sie diesen Held entlassen m\u00F6chten?",
	L"Eine Gruppe %s mit dem Bestreben nach gr\u00F6sserem Ruhm m\u00F6chte sich dir anschliessen. Bist du einverstanden?",
	L"Von der St\u00E4rke unserer Streitkr\u00E4fte beeindruckt, fliehen die %s. Willst du Sie verfolgen und stellen?",
	L"Dein Held kann eine dieser Zusatzfertigkeiten erlernen:",
	L"Dein Held hat erlernt:",
	L"Was w\u00E4hlst du?",
	L"Schaffe f\u00FCr die %s Platz in deiner Armee.",
	L"%s behauptet:",
	L"Ich nehme deine Kapitulation an und gew\u00E4hre dir und deiner Armee sicheres Geleit f\u00FCr den Preis von %d Gold.",
	L"Du brauchst %d Erfahrungspunkte, um die n\u00E4chste Stufe zu erreichen.",
	L"Gl\u00FCckwunsch! Alle unsere Feinde wurden vernichtet! Der Sieg ist unser!",
	L"All unsere Streitkr\u00E4fte wurden besiegt, du wurdest aus diesem Land verbannt!",
	L"%s Spieler wurde besiegt!",
	L"In der Armee ist kein Platz f\u00FCr diese Einheit.",
	L"Bist du sicher, dass du diese Runde beenden m\u00F6chtest?",
	L"Schauen Sie sich unsere feine Ware an. Wenn du etwas kaufen m\u00F6chtest, w\u00E4hle die Ware aus.",
	L"Ich biete dir an :",
	L"%s   f\u00FCr   %s",
	L"Du hast bereits vier Helden.",
	L"Es gibt keine Helden in der Taverne zum rekrutieren. Komme n\u00E4chste Woche wieder.",
	L"Dieser Zauber hat keinen Effekt!",
	L"Nicht genug Mana, um diesen Zauber zu beschw\u00F6ren.",
	L"Dieser Zauber ben\u00F6tigt %s Erfahrungspunkte auf Stufe %s.",
	L"%d Punkte Schaden",
	L"Diese Kreaturen sind bereit, sich uns anzuschliessen!",
	L"Diese schwachen Kreaturen werden mit Sicherheit fliehen.",
	L"Ich f\u00FCrchte diese Kreaturen sind bereit f\u00FCr einen Kampf.",
	L"Keinen Zauber ausgew\u00E4hlt",
	L"Dein Held ist zu m\u00FCde, um zu zaubern. Versuche es morgen nochmal.",
	L"Ben\u00F6tigt Held mit Stufe %d und Geschicklichkeit %s.",
	L"Ben\u00F6tigt Held mit Stufe %d.",
	L"Ben\u00F6tigt Held mit %s Geschicklichkeit.",
	L"Spieler %s ist am  Zug.",
	L"Spieler %s wird angegriffen!",
	L"Du h\u00E4ttest es besser wissen sollen - Du wirst angegriffen!",
	L"Das Graben nach Artefakten dauert einen ganzen Tag. Versuche es morgen nochmal.",
	L"Versuche es auf freier Ebene.",
	L"Gl\u00FCckw\u00FCnsch! Nachdem er viele Stunden hier gegraben hatte, hat dein Held die Krone des Eroberers gefunden.",
	L"Hier ist nichts. Wo k\u00F6nnte es sein?",
	L"Es gibt sieben verschiedene Ressourcen in Pocket Heroes, die ben\u00F6tigt werden, um Burgen zu bauen und zu verbessern, Truppen aufzubauen und Helden zu rekrutieren. Gold ist die wichtigste von ihnen und wird f\u00FCr nahezu alles ben\u00F6tigt. Holz und Erz braucht man f\u00FCr die meisten Geb\u00E4ude. Edelsteine, Quecksilber, Schwefel und Kristalle sind seltene magische Ressourcen, die f\u00FCr die m\u00E4chtigsten Kreaturen und Geb\u00E4ude ben\u00F6tigt werden.",
	L"Erfahrung wird ben\u00F6tigt, um in h\u00F6here Stufen aufzusteigen und so die Fertigkeiten des Helden zu verbessern.",
	L"Mana (Zauberpunkte) wird ben\u00F6tigt, um Zauber zu beschw\u00F6ren. Die maximale Manastufe ist zehnmal so hoch wie die Fertigkeit Wissen. Auftretende Ereignisse und Strukturen k\u00F6nnen die Manastufe zeitweise erh\u00F6hen.",
	L"Bewegungspunkte legen fest, wie weit sich Ihr Held jeden Tag bewegen kann. Die Strecke wird nach der Art des Gel\u00E4ndes, der Stra\u00DFen und der H\u00F6he Ihrer Fertigkeiten in Logistik und Pfadfinden berechnet. Spezielle F\u00E4lle, Ereignisse und Artefakte k\u00F6nnen die Zahl der Bewegungspunkte erh\u00F6hen.",
	L"Die Fertigkeit Angriff ist ein Bonus, der zum Angriffswert jeder Truppe deines Helden addiert wird. Du kannst so mehr Schaden im Kampf verursachen.",
	L"Die Fertigkeit Verteidigung ist ein Bonus, der zu dem Verteidigungswert jeder Truppe deines Helden addiert wird. Du kannst so mehr Schaden im Kampf abwehren. ",
	L"Zauberkraft legt die Dauer oder die St\u00E4rke eines Zaubers fest.",
	L"Die Fertigkeit Wissen legt die Zahl der Manapunkte deines Helden fest. Unter normalen Umst\u00E4nden wird ein Held auf 10 Zauberpunkte pro Stufe dieser Fertigkeit begrenzt.",
	L"Viel Gl\u00FCck erlaubt es deinen Truppen den doppelten Schaden im Kampf zu verursachen.",
	L"Mit neutralem Gl\u00FCck bleiben die Angriffe Ihrer Truppen unbeeinflu\u00DFt.",
	L"Ungl\u00FCck reduziert bei den betreffenden Einheiten den Angriffsschaden um die H\u00E4lfte.",
	L"Hohe Moral kann extra Angriffe bei den betreffenden Einheiten ausl\u00F6sen.",
	L"Bei neutraler Moral wird Ihre Armee nicht vor Angst erstarren. Allerdings wird sie auch keine Extra Angriffe durchf\u00FChren.",
	L"Schlechte Moral kann zur Folge haben, dass deine Truppen im Kampf gelegentlich aussetzen m\u00FCssen.",
	L"Das Zur\u00FCcksetzen des Highscores l\u00F6scht alles, was du bisher erreicht hast. Bist du sicher, dass du das machen m\u00F6chtest?",
	L"Neue Woche",
	L"Neuer Monat",
	L"Astrologen sagen den Monat der/des %s vorraus.",
	L"Astrologen sagen den Monat der PEST vorraus!",
	L"Astrologen sagen die Woche der/des %s vorraus.",
	L"Alle Geb\u00E4ude haben Bev\u00F6lkerungszuwachs.",
	L"Die Bev\u00F6lkerung wurde halbiert.",
	L"%s Bev\u00F6lkerung verdoppelt!",
	L"%s Wachstum +5.",
	L"Eichh\u00F6rnchens",
	L"Hasen",
	L"Erdh\u00F6rnchens",
	L"Dachses",
	L"Ratten",
	L"Adler",
	L"Wiesels",
	L"Raben",
	L"Mungos",
	L"Hunde",
	L"Erdferkel",
	L"Eisechsen",
	L"Schildkr\u00F6te",
	L"Igel",
	L"Kondore",
	L"Grash\u00FCpfers",
	L"Ameisen",
	L"Marienk\u00E4fers",
	L"Spinnen",
	L"Schmetterlings",
	L"Hummeln",
	L"Heuschrecken",
	L"Regenwurms",
	L"Wespen",
	L"K\u00E4fer",
	L"Schlachtfeld Opfer",
	L"Angreifer",
	L"Verteidiger",
	L"Kampfprotokoll",
	L"Hohe Moral erlaubt %s noch einmal anzugreifen.",
	L"Niedrige Moral veranla\u00DFt %s,  vor Panik zu erstarren.",
	L"Viel Gl\u00FCck gl\u00E4nzt auf %s",
	L"Ungl\u00FCck steigt auf %s herab",
	L"Runde %d",
	L"Angriff %s",
	L"Schuss %s",
	L" (%d Schaden)",
	L" (%d-%d Schaden)",
	L"%s haben %d Schaden erzeugt.",
	L"%d %s wurden besiegt.",
	L"%s pausieren und warten auf einen besseren Zeitpunkt um in Aktion zu treten.",
	L"%s nehmen eine defensive Position ein und gewinnen +%d Verteidigungsfertigkeit. ",
	L"Der Gefechtsturm macht %d Schaden.",
	L"Der Burggraben macht %d Schaden.",
	L"%s vernichten die H\u00E4lfte der feindlichem Truppen.",
	L"Beschw\u00F6re %s",
	L"Beschw\u00F6re %s zu %s.",
	L"%s beschw\u00F6rt %s.",
	L"%s beschw\u00F6rt %s zu %s.",
	L"Dieser %s Zauber macht %d Schaden.",
	L"Die %s widerstehen diesem Zauber",
	L"Du hast ein feindlicher Artefakt erobert!",
	L"Du hast %d feindliche Artefakte erobert!",
	L"Ein glorreicher Sieg!",
	L"Der Feind ist geflohen!",
	L"Der Feind hat kapituliert",
	L"F\u00FCr Heldenmut im Kampf, erh\u00E4lt %s %d Erfahrungspunkte.",
	L"Deine Streitkr\u00E4fte erleiden eine bittere Niederlage, %s gibt sein Vorhaben auf.",
	L"Deine Streitkr\u00E4fte erleiden eine bittere Niederlage,",
	L"Die feigen %s fliehen vor diesem Kampf.",
	L"%s kapituliert vor dem Feind und flieht in Schande.",
	L"%s setzt die Sph\u00E4re der Negation ein. Ein altes Artefakt, dass das Beschw\u00F6ren magischer Zauber verhindert.",
	L"%s beschw\u00F6rt den Fu\u00DFfesseln-des-Kriegers-Zauber. Du kannst nicht fliehen oder kapitulieren!",
	L"Du hast nicht genug Gold",
	L"\u00DCbe die dunklen K\u00FCnste der Totenbeschw\u00F6rung aus und du bist in der Lage, %d der get\u00F6teten Feinde als Skelette unter deiner F\u00FChrung auferstehen zu lassen...",
	L"Klein",
	L"Medium",
	L"Gro\u00DF",
	L"Extra Gro\u00DF",
	L"S",
	L"M",
	L"L",
	L"XL",
	L"Rang",
	L"Land",
	L"Datum",
	L"Tage",
	L"Punkte",
	L"Schwierigkeitsgrad",
	L"Einfach",
	L"Normal",
	L"Schwer",
	L"Experte",
	L"Unm\u00F6glich",
	L"Single Player",
	L"Neues Spiel starten",
	L"Multiplayer",
	L"Online Spiel",
	L"Hilfe",
	L"Tutorial",
	L"Laden",
	L"Speichern",
	L"Ruhmeshalle",
	L"Autoren",
	L"Einstellungen",
	L"Scenario neu starten",
	L"Hauptmen\u00FC",
	L"Beenden",
	L"Zur\u00FCck zum Spiel",
	L"Hot-Seat",
	L"Anzahl St\u00E4dte",
	L"Anzahl Helden",
	L"Ressourcen",
	L"gefundene Obelisken",
	L"Artefakte",
	L"Armeest\u00E4rke",
	L"Einkommen",
	L"Wasser",
	L"Strand",
	L"Dreck",
	L"Gras",
	L"Sumpf",
	L"Lava",
	L"\u00D6dland",
	L"W\u00FCste",
	L"Schnee",
	L"W\u00FCste",
	L"Weg",
	L"\u00D6dland",
	L"K\u00FCste",
	L"See",
	L"Spieler",
	L"Spieler",
	L"Rot",
	L"Gr\u00FCn",
	L"Blau",
	L"T\u00FCrkis",
	L"Lila",
	L"Gelb",
	L"Rot",
	L"Gr\u00FCn",
	L"Blau",
	L"T\u00FCrkis",
	L"Lila",
	L"Gelb",
	L"Undefiniert",
	L"Mensch",
	L"Computer",
	L"Nur Menschen",
	L"Nur Computer",
	L"Mensch oder Computer",
	L"Datum",
	L"Monat",
	L"Woche",
	L"Tag",
	L"M",
	L"W",
	L"T",
	L"Angriff",
	L"Verteidigung",
	L"Zauberkraft",
	L"Wissen",
	L"Sch\u00FCsse",
	L"Schaden",
	L"Gesundheit",
	L"Geschwindigkeit",
	L"Anzahl",
	L"Moral",
	L"Gl\u00FCck",
	L"Angriffslevel",
	L"Verteidigungslevel",
	L"Zauberkraft",
	L"Wissen",
	L"Sch\u00FCsse",
	L"Schaden",
	L"Gesundheit",
	L"Geschwindigkeit",
	L"Anzahl",
	L"Moral",
	L"Gl\u00FCck",
	L"Grundbesitz",
	L"F\u00FChrung",
	L"Gl\u00FCck",
	L"Diplomatie",
	L"Luftmagie",
	L"Erdmagie",
	L"Feuermagie",
	L"Wassermagie",
	L"Wissen",
	L"Totenbeschw\u00F6rung",
	L"Mystik",
	L"Intelligenz",
	L"Resistenz",
	L"Zauberei",
	L"Lernen",
	L"Kundschaften",
	L"Logistik",
	L"Pfadfinden",
	L"Fernkampf",
	L"Ballistik",
	L"Angriff",
	L"R\u00FCstung",
	L"Der Held steuert 250 Gold pro Tag zum Einkommen bei.",
	L"Der Held steuert 500 Gold pro Tag zum Einkommen bei.",
	L"Der Held steuert 1000 Gold pro Tag zum Einkommen bei.",
	L"Steigert die Moral der Truppen des Helden um 1.",
	L"Steigert die Moral der Truppen des Helden um 2.",
	L"Steigert die Moral der Truppen des Helden um 3.",
	L"Steigert das Gl\u00FCck des Helden um 1.",
	L"Steigert das Gl\u00FCck des Helden um 2.",
	L"Steigert das Gl\u00FCck des Helden um 3.",
	L"Erlaubt dir mit Monstern die schw\u00E4cher sind als deine Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 20%.",
	L"Erlaubt dir, mit Monstern die schw\u00E4cher sind als deine Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 40%.",
	L"Erlaubt dir, mit Monstern die schw\u00E4cher sind als deine Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 60%.",
	L"Einfache Luftmagie erlaubt deinem Helden Luft-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Luftmagie erlaubt deinem Helden Luft-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Experten Luftmagie erlaubt deinem Helden Luft-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Erdmagie erlaubt deinem Helden Erd-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Erdmagie erlaubt deinem Helden Erd-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Experten Erdmagie erlaubt deinem Helden Erd-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Feuermagie erlaubt deinem Helden Feuer-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Feuermagie erlaubt deinem Helden Feuer-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren",
	L"Experten Feuermagie erlaubt deinem Helden Feuer-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Wassermagie erlaubt deinem Helden Wasser-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Wassermagie erlaubt deinem Helden Wasser-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren",
	L"Experten Wassermagie erlaubt deinem Helden Wasser-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Erlaubt dem Helden Zauber der Sufe 3 zu erlernen.",
	L"Erlaubt dem Helden Zauber der Sufe 4 zu erlernen.",
	L"Erlaubt dem Helden Zauber der Sufe 5 zu erlernen.",
	L"Erlaubt 10% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt 20% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt 30% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt dem Helden 2 Zauberpunkte pro Tag zu regenerieren.",
	L"Erlaubt dem Helden 4 Zauberpunkte pro Tag zu regenerieren.",
	L"Erlaubt dem Helden 6 Zauberpunkte pro Tag zu regenerieren.",
	L"Steigert das Maximum der normalen Zauberpunkte des Helden um 25%.",
	L"Steigert das Maximum der normalen Zauberpunkte des Helden um 50%.",
	L"Verdoppelt das Maximum der normalen Zauberpunkte des Helden.",
	L"Stattet die Truppen eines Heldes mit 5% magischem Widerstand aus.",
	L"Stattet die Truppen eines Heldes mit 10% magischem Widerstand aus.",
	L"Stattet die Truppen eines Heldes mit 20% magischem Widerstand aus.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 5%.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 10%.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 15%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 5%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 10%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 15%.",
	L"Die Sicht deines Helden erweitert sich um 2 Felder.",
	L"Die Sicht deines Helden erweitert sich um 4 Felder.",
	L"Die Sicht deines Helden erweitert sich um 6 Felder.",
	L"Steigert die Bewegungspunkte des Helden um 10%.",
	L"Steigert die Bewegungspunkte des Helden um 20%.",
	L"Steigert die Bewegungspunkte des Helden um 30%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 25%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 50%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 75%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 10%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 25%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 50%.",
	L"Erlaubt einen gezielten Schuss mit erh\u00F6htem Schaden.",
	L"Erlaubt zwei gezielte Sch\u00FCsse mit erh\u00F6htem Schaden.",
	L"Erlaubt zwei gezielte Sch\u00FCsse mit maximalem Schaden.",
	L"Steigert den Nahkampf-Angriffsschaden um 10%.",
	L"Steigert den Nahkampf-Angriffsschaden um 20%.",
	L"Steigert den Nahkampf-Angriffsschaden um 30%.",
	L"Reduziert den Schaden, der den Truppen deines Helden zugef\u00FCgt wird um 5%.",
	L"Reduziert den Schaden, der den Truppen deines Helden zugef\u00FCgt wird um 10%.",
	L"Reduziert den Schaden, der den Truppen deines Helden zugef\u00FCgt wird um 15%.",
	L"Einfach",
	L"Fortgeschritten",
	L"Experte",
	L"Gold",
	L"Erz",
	L"Holz",
	L"Quecksilber",
	L"Edelsteine",
	L"Kristalle",
	L"Schwefel",
	L"Zuf\u00E4lliger Rohstoff",
	L"Goldhaufen",
	L"Erzhaufen",
	L"B\u00FCndel Holz",
	L"Flasche Quecksilber",
	L"Edelsteinhaufen",
	L"Kristallhaufen",
	L"Schwefelhaufen",
	L"Manakristall",
	L"Lagerfeuer",
	L"Schatzkiste",
	L"Lampe",
	L"Zauberrolle",
	L"Artefakt",
	L"Wache",
	L"Hoch auf deinem Ross, siehst du wie eine Wache zu dir tritt und sagt: \"Willkommen. Ich habe von deiner Ankunft geh\u00F6rt. M\u00F6chtest du passieren?\"",
	L"\"Niemand hat mir von deinem Kommen berichtet\", sagt der Grenzposten. \"Ich kann dich nicht passieren lassen. Vielleicht solltest du zuerst das Zelt des Schl\u00FCsselmeisters aufsuchen\".",
	L"Nachdem Du den Bereich ausgekundschaftet hast, stolperst Du \u00FCber einen versteckten Schatz. Du kannst das Gold nehmen oder es f\u00FCr Erfahrungspunkte unter den Bauern verteilen.",
	L"Du findest eine Spruchrolle, die mit dem %s Zauber beschrieben ist.",
	L"Ereignis",
	L"",
	L"Zuf\u00E4llig",
	L"Zuf\u00E4llig (Level 1)",
	L"Zuf\u00E4llig (Level 2)",
	L"Zuf\u00E4llig (Level 3)",
	L"Zuf\u00E4llig (Level 4)",
	L"Zuf\u00E4llig (Level 5)",
	L"Zuf\u00E4llig (Level 6)",
	L"\u0421\u043B\u0443\u0447\u0430\u0439\u043D\u044B\u0439",
	L"Zuf\u00E4llig (Level 1)",
	L"Zuf\u00E4llig (Level 2)",
	L"Zuf\u00E4llig (Level 3)",
	L"Zuf\u00E4llig (Level 4)",
	L"Loch",
	L"Spalt",
	L"Skelett",
	L"Blumen",
	L"Pilz",
	L"Fels",
	L"Baumstumpf",
	L"Holzscheit",
	L"Kaktur",
	L"Busch",
	L"B\u00E4ume",
	L"Palme",
	L"Kiefer",
	L"Eiche",
	L"Toter Baum",
	L"Vulkan",
	L"Berg",
	L"See",
	L"Wall",
	L"Schlammige Stra\u00DFe",
	L"Steinige Stra\u00DFe",
	L"Verschneite Stra\u00DFe",
	L"Fluss",
	L"Lavafluss",
	L"",
	L"Lichtstein",
	L"Holzschild",
	L"Aussichtsturm",
	L"Medusatempel",
	L"Diebeswagen",
	L"W\u00FCstenzelt",
	L"Geisterhaus",
	L"Steinbrunnen",
	L"Gartenlaube",
	L"Baum des Wissens",
	L"Monolyt",
	L"Windm\u00FChle",
	L"Schrein des ersten Kreises",
	L"Schrein des zweiten Kreises",
	L"Schrein des dritten Kreises",
	L"Stallungen",
	L"G\u00F6tzenbild",
	L"Dreieinigkeit",
	L"Springbrunnen",
	L"Tempel",
	L"Schwert im Stein",
	L"Fort",
	L"Schmiede",
	L"Steinkreis",
	L"Magischer Stein",
	L"Prophetenstatue",
	L"Arena",
	L"Bibliothek",
	L"Obelisk",
	L"Magischer Brunnen",
	L"Garten des Wissens",
	L"Hexenh\u00FCtte",
	L"Schiffswrack",
	L"Eish\u00F6hle",
	L"Pyramide",
	L"Tempel der Inti",
	L"Schatz der Oger",
	L"Schatz der Magier",
	L"Schatz der Hydra",
	L"Schatz der Medusa",
	L"Schatz der Gargoyles",
	L"Schatz der Druiden",
	L"Magische Zitadelle",
	L"Kloster",
	L"Mausoleum",
	L"Magische Schule",
	L"Pegasus Wasserfall",
	L"Wei\u00DFe Wolfsh\u00F6hle",
	L"Wolfsh\u00F6hle",
	L"Sarg",
	L"Vampirsarg",
	L"Wolfsh\u00F6hle alt",
	L"Wildscheinh\u00F6hle alt",
	L"Schwertk\u00E4mpfer Arsenal alt",
	L"Halblingsh\u00FCtte alt",
	L"Platzhalter",
	L"Zelt des Schl\u00FCsselmeisters",
	L"Gie\u00DFerei",
	L"Lehmh\u00FCtte des Ogers",
	L"Mumiensarg",
	L"Elfenhaus",
	L"Druidenstein",
	L"Greifennest",
	L"Ein Schluck aus der Quelle hat deine Zauberpunkte erneuert.",
	L"Ein alter Ritter erscheint auf den Stufen der Gartenlaube \"Mein Lehnsherr, ich werde euch all mein Wissen lehren um euch auf euren Reisen Beistand leisten zu k\u00F6nnen.\"",
	L"Auf deine Ann\u00E4herung hin \u00F6ffnet der Baum vergn\u00FCgt seine Augen: \"Aah, ein Abenteurer! Erlaube mir, dir ein wenig von dem beizubringen, was ich \u00FCber die Jahre gelernt habe.\"",
	L"Als du dich n\u00E4herst, beginnt der Monolit zu leuchten. Du entscheidest dich, die Symbole auf ihre Bedeutung hin zu erforschen.",
	L"Der Besitzer der M\u00FChle erkl\u00E4rt: \"Mein Lord, ich habe sehr hart gearbeitet um euch mit diesen Rohstoffen zu beliefern, n\u00E4chste Woche gibt es weitere Rohstoffe.\"",
	L"Du kommst an einem kleinen Schrein vorbei, der von einer Gruppe Akolythen bewacht wird. Im Gegenzug f\u00FCr deinen Schutz willigen sie ein, dir einen einfachen Zauber beizubringen - ",
	L"Du kommst an einem kunstvoll verzierten Schrein vorbei, der von wohlgen\u00E4hrten M\u00F6nchen bewacht wird. Im Gegenzug f\u00FCr deinen Schutz willigen sie ein, dir einen Zauber beizubringen - ",
	L"Du kommst an einem verschwenderisch verzierten Schrein vorbei, der von einer Gruppe Hohepriestern bewacht wird. Im Gegenzug f\u00FCr deinen Schutz willigen sie ein, dir einen anspruchsvollen Zauber beizubringen - ",
	L"Als du in den Stallungen eintriffst kommt dir der Stallbursche mit einem edlen Schlachtross entgegen: \"Dieses Pferd wird deine Reisen beschleunigen. Leider wird seine Ausdauer nach langen Reisen sinken. Du musst f\u00FCr ein frisches Reittier jede Woche zur\u00FCckkehren.\"",
	L"Du hast ein uraltes, verwittertes G\u00F6tzenbild endtdeckt. Angeblich bringt ein Kuss des G\u00F6tzenbilds Gl\u00FCck - der Stein f\u00FChlt sich sehr kalt an.",
	L"Das ist alles, was ich die Woche \u00FCber gesammelt habe. Benutze das Gold gut \u00FCberlegt.",
	L"Ein Schluck des s\u00FC\u00DFen Wassers bringt dir Gl\u00FCck f\u00FCr den n\u00E4chsten Kampf.",
	L"Ein Besuch und ein Gebet im Tempel erh\u00F6ht die Moral deiner Truppen.",
	L"Du hast einige Stunden mit dem Versuch verbracht, das Schwert aus dem Stein zu ziehen - es hat sich noch keinen Zentimeter bewegt\u2026 Aber \u00E4rgere dich  nicht - deine Armee hat sich w\u00E4hrenddessen ausgeruht und f\u00FCr dich war es eine gute \u00DCbung!",
	L"Die Stunde, die du im Fort verbracht hast, zeigte dir der Meister neue Verteidigungstechniken.",
	L"Du erreichst eine Schmiede\u2026 Als du hineingehst siehst du einen Waffenschmied bei der Arbeit. Er legt seinen Hammer zur Seite und sagt: \"Ich kann Deine R\u00FCstung reparieren!\"",
	L"Du hast eine Gruppe Druiden gefunden die eines ihrer seltsamen steinernen Geb\u00E4ude verehren. Leise bringen Sie dir neue Wege zu zaubern bei.",
	L"Du hast eine Gruppe Heiden gefunden, die an einem fremden gl\u00FChenden Stein beten. Du trittst dem Ritual bei. Leise bringen Sie dir neue Wege zu zaubern bei.",
	L"Du ber\u00FChrst die Statue des Propheten und sp\u00FCrst wie deine Macht steigt.",
	L"Du betrittst die Arena und siehst dich einer Horde hungriger L\u00F6wen gegen\u00FCber. Unter lauten Jubelrufen der Menge besiegst du Sie. Beeidruckt von deinen Fertigkeiten, willigt der alte Gladiatoren ein, dich in Angriff und Verteidigung zu trainieren.",
	L"Der W\u00E4rter l\u00E4sst dich in die Bibliothek der Erleuchtung ein. Du kannst viel lernen in der kurzen Zeit die du hier verbringst.",
	L"Du erreichst einen Obelisken, der aus einer Steinart beschaffen ist, die du noch niemals zuvor gesehen hast. Als du den Obelisken genauer untersuchst ver\u00E4ndert sich pl\u00F6tzlich die glatte Oberfl\u00E4che des Steins zu einer Inschrift. Die Inschrift ist Teil einer uralten Karte. Schnell zeichnest du die sonderbaren Muster ab und genauso schnell wie sie aufgetaucht ist, verschwindet die Inschrift auch wieder.",
	L"Ein Schluck aus der Quelle f\u00FCllt deine Adern mit Magie! Du hast nun doppelt soviele Zauberpunkt als normal in Reserve.",
	L"Ein M\u00F6nch, der in der Mitte eines Gartens sitzt, l\u00E4dt dich ein mit ihm zu meditieren. Du willigst ein und bereits nach kurzer Zeit f\u00FChlst du dich erleuchtet.",
	L"Der W\u00E4chter dieses Schl\u00FCsselmeisterzeltes scheint gl\u00FCcklich zu sein dich zu sehen. \"Ah, endlich jemand W\u00FCrdiges\", sagt er. \"Ich werde sofort eine Nachricht an die Grenzwache losschicken, dass du passieren darfst.\"",
	L"Zweimal in einer Woche aus der Quelle zu trinken wird dir nicht weiterhelfen.",
	L"Ein alter Ritter erscheint auf den Stufen der Gartenlaube \"Mein Lehnsherr, es tut mir leid, aber ich habe ihnen bereits alles beigebracht was ich wusste.\"",
	L"Der Baum oeffnet die Augen und sagt: \"Ich hoffe, mein Unterricht hat dir geholfen\".",
	L"Auf deine Ann\u00E4herung hin ,erlischt das Licht des Monoliths.",
	L"Der M\u00FCller sagt euch: \"Mein Lord es tut mir Leid, leider habe ich zur Zeit keine Rohstoffe f\u00FCr euch. Kommt doch bitte n\u00E4chste Woche noch einmal vorbei.\"",
	L"Der Stallbursche taucht auf und sagt:\"Du hast bereits ein frisches Pferd.\"",
	L"Du hast ein uraltes, verwittertes G\u00F6tzenbild endtdeckt. Angeblich bringt ein Kuss des G\u00F6tzenbilds Gl\u00FCck - aber da die Sterne bereits auf dich hinabscheinen, passiert nichts.\"",
	L"Ich habe kein weiteres Gold f\u00FCr dich. Komm morgen wieder.",
	L"Du trinkst von der verzauberten Quelle, aber nichts passiert.",
	L"Es hilft nicht zweimal vor einem Kampf zu beten.",
	L"Dieses Schwert steckt im Stein fest! Keine Chance es herauszubekommen!",
	L"Ich habe dir bereits alles beigebracht was ich kann. Ich will meine Zeit mit dir nicht weiter verschwenden, also verschwinde!",
	L"Du erreichst eine Schmiede. Als du hineingehst, siehst du einen Waffenschmied bei der Arbeit. Er untersucht dein Schild und sagt: \"Das Schild muss nicht repariert werden. Ich habe bereits alles f\u00FCr dich getan was ich konnte.\"",
	L"Du hast eine Gruppe Druiden gefunden, die eines ihrer seltsamen steinernen Geb\u00E4ude verehren. Leise wenden Sie sich von dir ab, dir zeigend, dass Sie dir nichts Neues beibringen k\u00F6nnen.",
	L"Du hast eine Gruppe von Heiden gefunden, die an einem fremden gl\u00FChenden Stein beten. Leise wenden Sie sich von dir ab, dir zeigend, dass Sie dir nichts Neues beibringen k\u00F6nnen.",
	L"Du ber\u00FChrst die Statue, aber nichts passiert. Als du die Statue ein zweites Mal ber\u00FChrst f\u00E4ngt Sie pl\u00F6tzlich zu sprechen an: \"Ich hab dir meine magische Kraft verliehen und trotzdem gehst du mir weiter auf die Nerven!? Verschwinde!\"",
	L"Die Wachen der Arena halten dich vom Eintreten ab: \"Du hast bereits unsere Besten besiegt. Du kannst gehen.\"",
	L"Sich an dich erinnernd weigert sich der W\u00E4rter dich einzulassen: \"Die Bibliothek der Erleuchtung\", sagt er, \"darf nur einmal besucht werden.\"",
	L"Du hast diesen Obelisk bereits besucht.",
	L"Die magische Quelle regeneriert sich nur einmal jede Woche, und irgendjemand war bereits hier diese Woche.",
	L"Du betrittst den Garten, und der M\u00F6nch, sich an dich erinnernd, sagt, \"Mein Kind, der Segen der Weisheit \u00FCberkommt einen nur einmal in seinem Leben.\"",
	L"Der W\u00E4chter dieses Zelts des Schl\u00FCsselmeisters erinnert sich an dich als du n\u00E4her kommst. \"Ich habe bereits Nachricht geschickt, dass es dir erlaubt ist zu passieren,\" sagt er.",
	L"Ungl\u00FCcklicherweise hast du noch nicht das Wissen den Spruch zu verstehen weswegen du ihn auch noch nicht erlernen kannst.",
	L"In einer seltsamen H\u00FCtte hei\u00DFt dich eine uralte Hexe willkommen - aus r\u00E4tselhaften Gr\u00FCnden bringst sie dir %s bei.",
	L"Du erreichst eine seltsame H\u00FCtte und beobachtest wie innen eine Hexe ein Buch \u00FCber %s studiert. Als du dich n\u00E4herst, dreht sie sich um und sagt: \"Du wei\u00DFt bereits was ich dir beibringen wollte. Ich kann dir nicht weiterhelfen.\"",
	L"Du erreichst eine seltsame H\u00FCtte und beobachtest wie innen eine Hexe ein Buch \u00FCber %s studiert. Als du dich n\u00E4herst, dreht sie sich um, fixiert dich mit ihren Glasauge und kreischt: \"Hah, ich werde nicht versuchen jemandem der so weise ist wie Du etwas beizubringen.\" Du verl\u00E4sst die H\u00FCtte, kannst aber das ungute Gef\u00FChl nicht absch\u00FCtteln.",
	L"M\u00F6chtest du %s rekrutieren?",
	L"%d %s schlie\u00DFen sich dir an.",
	L"Hier gibt es keine %s mehr zu rekrutieren.",
	L"Du entdeckst einen l\u00E4ngst verlassenen Ort: %s.",
	L"Nachdem du die Wachen besiegt hast entdeckst du: ",
	L"Einseitiger Eingang",
	L"Einseitiger Ausgang",
	L"Zweiwegeportal",
	L"Dieses Bauwerk ist offensichtlich eine Reisepforte, sie erscheint aber nicht l\u00E4nger funktionsf\u00E4hig zu sein.",
	L"Sp\u00E4hturm",
	L"Beobachtungsturm",
	L"Von deinem Sp\u00E4hturm aus kannst du weit entfernte L\u00E4nder sehen.",
	L"Von deinem Beobachtungsturm aus kannst du weit entfernte L\u00E4nder sehen. Alle deine Helden erhalten eine +1 Bewegungsbonus.",
	L"Goldmine",
	L"Erzgrube",
	L"S\u00E4gem\u00FChle",
	L"Alchemielabor",
	L"Edelsteinmine",
	L"Kristallmine",
	L"Schwefelmine",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber eine Goldmine. Sie wird dich mit 1000 Gold pro Tag versorgen.",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber eine Erzgrube. Sie wird dich mit zwei Einheiten Erz pro Tag versorgen.",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber ein S\u00E4gewerk. Es wird dich mit zwei Einheiten Holz pro Tag versorgen.",
	L"",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber eine Edelsteinmine. Sie wird dich mit einer Einheit Edelsteinen pro Tag versorgen.",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber eine Kristallmine. Sie wird dich mit einer Einheit Kristallen pro Tag versorgen.",
	L"Du erh\u00E4ltst die Kontrolle \u00FCber eine Schwefelmine. Sie wird dich mit einer Einheit Schwefel pro Tag versorgen.",
	L"Stadtportal",
	L"Bereits Besucht",
	L"Nicht besucht",
	L"Ritter",
	L"Barbar",
	L"Zauberer",
	L"Hexenmeister",
	L"Zauberin",
	L"Totenbeschw\u00F6rer",
	L"Gerald",
	L"Fineous",
	L"Jacob",
	L"Schultz",
	L"Cantor",
	L"Bez",
	L"Earoon",
	L"Hedric",
	L"Tyrex",
	L"Grottekvarnen",
	L"Yog",
	L"Jaclyn",
	L"Krag",
	L"Baraka",
	L"Hapax",
	L"Krull",
	L"Cronus",
	L"Iona",
	L"Bernhard",
	L"Posid",
	L"Malcom",
	L"Morgana",
	L"Victor",
	L"Visarus",
	L"Gallatin",
	L"Altus",
	L"Odin",
	L"Kastore",
	L"Alamar",
	L"Eldor",
	L"Fondo",
	L"Marcus",
	L"Jack",
	L"Ferentona",
	L"Gem",
	L"Arven",
	L"Samira",
	L"Myrini",
	L"Rebecca",
	L"Dvergar",
	L"Rait",
	L"Urof",
	L"Tamika",
	L"Shra",
	L"Ruthven",
	L"Ranloo",
	L"Sandru",
	L"Knecht Ruprecth",
	L"Zuf\u00E4llig",
	L"Zitadelle",
	L"Hochburg",
	L"Turm",
	L"Verlie\u00DF",
	L"Festung",
	L"Nekropolis",
	L"Klein",
	L"Mittel",
	L"Gro\u00DF",
	L"Bauernh\u00FCtte",
	L"Bogensch\u00FCtzenturm",
	L"Wachhaus",
	L"Abtei",
	L"Turnierplatz",
	L"Kathedrale",
	L"Goblinbaracken",
	L"Orkturm",
	L"Wolfsbau",
	L"Ogerfort",
	L"Trollbr\u00FCcke",
	L"Zyklopenh\u00F6hle",
	L"Magische Schule",
	L"Wolfsh\u00F6hle",
	L"Fabrik",
	L"Magische Wolke",
	L"Magierturm",
	L"Wolkenschloss",
	L"Zentaurenh\u00F6hle",
	L"Gruft",
	L"Greifenturm",
	L"Labyrinth",
	L"Hydrateich",
	L"Drachenh\u00F6hle",
	L"Baumhaus",
	L"Zwergenh\u00E4uschen",
	L"Geh\u00F6ft",
	L"Druidenzirkel",
	L"Einhornlichtung",
	L"Roter Turm",
	L"Ausgrabungsst\u00E4tte",
	L"Friedhof",
	L"Grabmal",
	L"Haus der S\u00E4rge",
	L"Dunkles Grab",
	L"Verfluchter Turm",
	L"Magiergilde 1",
	L"Magiergilde 2",
	L"Magiergilde 3",
	L"Magiergilde 4",
	L"Magiergilde 5",
	L"Magischer Knoten",
	L"Taverne",
	L"Marktplatz",
	L"Ratshaus",
	L"Stadthalle",
	L"Erzgrube",
	L"S\u00E4gewerk",
	L"Alchemielabor",
	L"Edelsteinmine",
	L"Kristallmine",
	L"Schwefelmine",
	L"Burggraben",
	L"Hauptgesch\u00FCtzturm",
	L"Linker Gesch\u00FCtzturm",
	L"Rechter Gesch\u00FCtzturm",
	L"Schie\u00DFplatz",
	L"Gerichtshalle",
	L"Eichenwald",
	L"Wasserfall",
	L"Bergmannsgilde",
	L"Offene Gr\u00E4ber",
	L"Aussichtsturm",
	L"Befestigungen",
	L"Halle der Vorfahren",
	L"Lehmstein",
	L"Wall der Weisheit",
	L"Bibliothek",
	L"Altar",
	L"Manawirbel",
	L"Schatzkammer",
	L"Mystischer Teich",
	L"Verst\u00E4rker der Totenbeschw\u00F6rer",
	L"Schleier der Dunkelheit",
	L"%s erlaubt dir %s zu rekrutieren.",
	L"Das Betreten der Magiergilde l\u00E4sst einen anwesenden Helden die Spr\u00FCche der Gilde lernen.",
	L"Stellt pro Tag 1 Manapunkt f\u00FCr alle verb\u00FCndeten Helden wieder her.",
	L"Die Taverne erm\u00F6glicht es Helden anzuheuern und erh\u00F6ht die Moral der Truppen, die die Stadt verteidigen.",
	L"Auf dem Marktplatz kannst du Rohstoffe kaufen und verkaufen (Die Tarife verbessern sich je mehr Marktpl\u00E4tze du besitzt).",
	L"Das Rathaus verbessert das Einkommen deines Reiches um 500 Gold jeden Tag.",
	L"Die Stadthalle erh\u00F6ht das Einkommen deines Reiches um 1500 Gold pro Tag.",
	L"Die Erzgrube versorgt dich mit einer zus\u00E4tzlichen Einheit Erz jeden Tag.",
	L"Das S\u00E4gewerk versorgt dich mit einer zus\u00E4tzlichen Einheit Holz jeden Tag.",
	L"Das Alchemielabor versorgt dich mit einer zus\u00E4tzlichen Einheit Quecksilber jeden Tag.",
	L"Die Edelsteinmine versorgt dich mit einer zus\u00E4tzlichen Einheit Edelsteinen jeden Tag.",
	L"Die Kristallmine versorgt dich mit einer zus\u00E4tzlichen Einheit Kristall jeden Tag.",
	L"Die Schwefelmine versorgt dich mit einer zus\u00E4tzlichen Einheit Schwefel jeden Tag.",
	L"Der Burggraben verlangsamt angreifende Einheiten. Jede Einheit die den Burggraben betritt muss ihren Zug dort beenden und wird verwundbarer gegen\u00FCber Attacken.",
	L"Der Hauptgesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"Der linke Gesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"Der rechte Gesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"%s erh\u00F6ht die Produktion von %s um %d pro Woche.",
	L"Der Aussichtsturm erh\u00F6ht die sichtbare Fl\u00E4che um deine Stadt, und alle deine Helden erhalten +5 Reisepunkte als Bonus.",
	L"Befestigungen verbessern die Haltbarkeit von Burgw\u00E4llen w\u00E4hrend einer Belagerung.",
	L"Die Halle der Vorfahren steigert die Angriff F\u00E4higkeit jedes Helden der sie besucht um 1.",
	L"Die Halle der Weisheit erh\u00F6ht die Weisheit jedes Helden der sie besucht um 1.",
	L"Die Bibliothek \u00E4ndert zuf\u00E4llig einige der Zauber in deiner Magiergilde am Anfang jedes Monats.",
	L"Der Altar erh\u00F6ht das Einkommen deines Reiches um 1000 Gold pro Tag.",
	L"Der Manawirbel verdoppelt vor\u00FCbergehend die Zauberpunkte eines Helden der ihn besucht.",
	L"Die Schatzkammer erh\u00F6ht das Einkommen deines Reiches um 1000 Gold pro Tag.",
	L"Der Mystische Teich produziert jede Woche eine geringe Menge Rohstoffe.",
	L"Der Verst\u00E4rker der Totenbeschw\u00F6rer erh\u00F6ht die Totenbeschw\u00F6rerf\u00E4higkeit aller deiner Helden (mit Totenbeschw\u00F6rerf\u00E4higkeit) um 10%.",
	L"Der Schleier der Dunkelheit verbirgt deine Stadt dauerhaft vor allen anderen Spielern.",
	L"Der Teich hat noch nichts produziert.",
	L"Der Teich hat diese Woche %s produziert.",
	L"Silberschwert",
	L"Bauernsichel",
	L"Brustplatte",
	L"Drachenschild",
	L"M\u00F6nchsring",
	L"Hexenbrosche der Magie",
	L"Unbedeutende Schriftrolle der Weisheit",
	L"Pergamentrolle",
	L"Anh\u00E4nger der Weisheit",
	L"Ehrenmedaille",
	L"Medaille",
	L"Gl\u00FCcksw\u00FCrfel",
	L"Gl\u00FCckskleeblatt",
	L"Silberner Gl\u00FCcksvogel",
	L"Langbogen",
	L"Ring der Untoten",
	L"Teleskop",
	L"Sch\u00FCtzende Luftrobe",
	L"Sch\u00FCtzende Erdrobe",
	L"Sch\u00FCtzende Feuerrobe",
	L"Sch\u00FCtzende Wasserrobe",
	L"Manakrug",
	L"M\u00E4chtige Axt",
	L"Kriegerhelm",
	L"Beschw\u00F6rerarmschienen",
	L"Schriftrolle der Erleuchtung",
	L"Stachelhelm",
	L"Der Ring des Weisen",
	L"Weisse Perlenkette",
	L"Goldener Gl\u00FCcksvogel",
	L"Unersch\u00F6pflicher Erzkarren",
	L"Unersch\u00F6pfliches Holzklafter",
	L"Ring des Lebens",
	L"Anh\u00E4nger des Lebens",
	L"Elfenbogen",
	L"Vampirkutte",
	L"Stiefel des Reisenden",
	L"Federkiel der Diplomatie",
	L"Robe des Widerstands",
	L"Robe der Gewandheit",
	L"Verzaubertes Schwert",
	L"M\u00E4chtige R\u00FCstung",
	L"Ring der Kraft",
	L"Buch der Erkenntnis",
	L"Antikes Breitschwert",
	L"Zwergenschild",
	L"Schild des Paladins",
	L"Stab der Hexerei",
	L"Bedeutende Schriftrolle der Erkenntnis",
	L"Buch der Weisheit",
	L"Finsternis",
	L"Schlangenarmreif",
	L"Schwarze Perlenkette",
	L"Anh\u00E4nger der Allwissenheit",
	L"Ring der Ewigkeit",
	L"Armbrust",
	L"Schwert der Untoten",
	L"Unersch\u00F6pfliche Goldb\u00F6rse",
	L"Unersch\u00F6pflicher Goldsack",
	L"Amulett des Reichtums",
	L"Unersch\u00F6pfliche Quecksilberphiole",
	L"Unersch\u00F6pflicher Edelsteinbeutel",
	L"Schwefelring",
	L"Kristallrose",
	L"Nomadenstiefel",
	L"Langschwert",
	L"Heldenschild",
	L"Helm der Vorboten",
	L"Zaubererhut",
	L"Schwertbrecher",
	L"Halsband des Hexenmeisters",
	L"Sph\u00E4re des Negation",
	L"Zauberstab",
	L"Fu\u00DFfesseln des Kriegers",
	L"Krone des Eroberers",
	L"Wurfaxt",
	L"Goblin Schild",
	L"Zauberanh\u00E4nger",
	L"Verfluchtes Schwert",
	L"Sph\u00E4re der Luft",
	L"Sph\u00E4re der Erde",
	L"Sph\u00E4re des Feuers",
	L"Sph\u00E4re des Wassers",
	L"Eiserne Schlagkugel",
	L"Goldene Schlagkugel",
	L"Goldenes Schwert",
	L"Goldenes Schild",
	L"Goldene R\u00FCstung",
	L"Goldener Sch\u00E4del",
	L"Eiserne Beinschienen",
	L"Kn\u00F6cherne Beinschienen",
	L"Schwert des Bastards",
	L"Luftdiadem",
	L"J\u00E4gershut",
	L"Lederr\u00FCstung",
	L"Goblinhut",
	L"Knochenkette",
	L"Zwergenhelm",
	L"Reiterhelm",
	L"Ogerschild",
	L"Pfeile",
	L"Sonnenstab",
	L"Zwergenhammer",
	L"Fl\u00FCgelhelm",
	L"Knochenmaske",
	L"Knochenr\u00FCstung",
	L"K\u00F6nigsschild",
	L"Blutstein-Kette",
	L"Schneller Bogen",
	L"Sumpfschuhe",
	L"Eisamulett",
	L"Steigert deinen Angriff um 1.",
	L"Steigert deinen Angriff um 1, erh\u00F6ht den Angriff der Bauern um 3.",
	L"Steigert deine Verteidigung um 1 und die der Kavallerie um 2.",
	L"Steigert deine Verteidigung um 1 und die Drachenverteidigung um 5.",
	L"Steigert deine Zauberkraft um 1 und die der M\u00F6nche um 3.",
	L"Steigert deine Zauberkraft um 1.",
	L"Steigert dein Wissen um 1.",
	L"Steigert dein Wissen um 1.",
	L"Steigert dein Wissen um 1.",
	L"Steigert deine Moral um 1.",
	L"Steigert deine Moral um 1.",
	L"Steigert dein Gl\u00FCck um 1.",
	L" Steigert dein Gl\u00FCck um 1.",
	L"Steigert dein Gl\u00FCck um 1.",
	L"Steigert deine Fernkampffertigkeit um 5%.",
	L"Steigert deine Totenbeschw\u00F6rerfertigkeit um 5%.",
	L"Erlaubt deinem Helden 1 Feld weiter zu sehen.",
	L"Luftmagiezauber verursachen 30% weniger Schaden.",
	L"Erdmagiezauber verursachen 30% weniger Schaden.",
	L"Feuermagiezauber verursachen 30% weniger Schaden.",
	L"Wassermagiezauber verursachen 30% weniger Schaden.",
	L"Stellt 2 zus\u00E4tzliche Zauberpunkte pro Tag wieder her.",
	L"Erh\u00F6ht Angriff und Verteidigung um 1.",
	L"Steigert deine Verteidigung um 2.",
	L"Steigert deine Zauberkraft um 2.",
	L"Steigert dein Wissen um 2.",
	L"Erh\u00F6ht Angriff und Verteidigung um 1.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 1.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 1.",
	L"Steigert dein Gl\u00FCck um 2.",
	L"Versorgt dich mit einer zus\u00E4tzlichen Einheit Erz pro Tag.",
	L"Versorgt dich mit einer zus\u00E4tzlichen Einheit Holz pro Tag.",
	L"Erh\u00F6ht die Gesundheit aller deiner Einheiten um 1.",
	L"Erh\u00F6ht die Gesundheit aller deiner Einheiten um 2.",
	L"Steigert deine Fernkampf Fertigkeit um 10% und den Angriff der Elfen um 3.",
	L"Steigert deine Totenbeschw\u00F6rerfertigkeit um 10% und die Verteidigung der Vampire um 1.",
	L"Erh\u00F6ht deine Bewegungspunkte an Land um 20.",
	L"Senkt die Kosten einer Kapitulation um 20%.",
	L"Erh\u00F6ht deine Magische Resistenz um 10%.",
	L"Erh\u00F6ht die Kampfgeschwindigkeit aller deiner Einheiten um 1.",
	L"Steigert deinen Angriff um 3.",
	L"Steigert deine Verteidigung um 3.",
	L"Steigert deine Zauberkraft um 3.",
	L"Steigert dein Wissen um 3.",
	L"Steigert deinen Angriff um 4.",
	L"Steigert deine Verteidigung um 4.",
	L"Steigert deine Verteidigung um 4 und die der Paladine um 2.",
	L"Steigert deine Zauberkraft um 4.",
	L"Steigert dein Wissen um 4.",
	L"Steigert dein Wissen um 4.",
	L"Erh\u00F6ht Angriff und Verteidigung um 2.",
	L" Erh\u00F6ht Zauberkraft und Wissen um 2.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 2.",
	L"Erh\u00F6ht Angriff, Verteidigung, Zauberkraft und Wissen jeweils um 1.",
	L"Erh\u00F6ht die Gesundheit aller deiner Einheiten um 3.",
	L"Steigert deine Fernkampf Fertigkeit um 15%.",
	L"Steigert deine Totenbeschw\u00F6rerfertigkeit um 15%.",
	L"Steigert dein Einkommen um 500 Gold pro Tag.",
	L"Steigert dein Einkommen um 750 Gold pro Tag.",
	L"Steigert dein Einkommen um 1000 Gold pro Tag.",
	L"Versorgt dich t\u00E4glich mit einer zus\u00E4tzlichen Einheit Quecksilber.",
	L" Versorgt dich t\u00E4glich mit einer zus\u00E4tzlichen Einheit Edelsteinen.",
	L"Versorgt dich t\u00E4glich mit einer zus\u00E4tzlichen Einheit Schwefel.",
	L"Versorgt dich t\u00E4glich mit einer zus\u00E4tzlichen Einheit Kristall.",
	L"Erh\u00F6ht deine Bewegungspunkte an Land um 30 und die Geschwindigkeit der Normaden um 3.",
	L"Steigert deinen Angriff um 6.",
	L"Steigert deine Verteidigung um 6.",
	L"Steigert deine Zauberkraft um 6.",
	L"Steigert dein Wissen um 6.",
	L"Erh\u00F6ht deinen Angriff und dein Verteidigung um 3.",
	L"Erh\u00F6ht deine Zauberkraft und dein Wissen um 3.",
	L"Erh\u00F6ht deinen Angriff, deine Verteidigung, deine Zauberkraft und dein Wissen jeweils um 2.",
	L"Weder du noch dein Gegner d\u00FCrfen fliehen oder aufgeben.",
	L"Verhindert jegliches Aussprechen von Zaubern w\u00E4hrend des Kampfes.",
	L"Jede Heldenklasse erh\u00E4lt ihren Spezial Bonus &",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen deiner Helden jeweils um 4. Erh\u00F6ht die Bewegungspunkte des Helden \u00FCber Land um 10%. Erh\u00F6ht die Kampfgeschwindkeit aller Einheiten um 2.",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen deiner Helden jeweils um 4. Stattet die Truppen des Helden mit 50% magischer Resistenz aus und erlaubt es ihnen, ohne Abz\u00FCge f\u00FCr Reichweite oder Hindernisse zu schie\u00DFen.",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung deiner Helden um 4, Zauberkraft und Wissen um 6. Erh\u00F6ht die Effektivit\u00E4t von Beschw\u00F6rungs- und Wiederbelebungsspr\u00FCchen um 50%.",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung deiner Helden um 4, Zauberkraft und Wissen um 6. Regeneriert jeden Tag alle Zauberpunkte.",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung deiner Helden um 4, Zauberkraft und Wissen um 6. Erh\u00F6ht den Schaden aller zerst\u00F6rerischen Spr\u00FCche um 50%.",
	L"Erh\u00F6ht dein Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen deiner Helden jeweils um 4. Erh\u00F6ht deine Totenbeschw\u00F6rerfertigkeit um 15%. L\u00E4sst Tote als Vampire wiederauferstehen.",
	L"Erh\u00F6ht deinen Angriff um 2.",
	L"Erh\u00F6ht deine Verteidigung um 4 und die der Goblins um 3.",
	L"Erh\u00F6ht deine Zauberkraft um 2.",
	L"Versteckt deinen Helden vor den anderen Spielern durch ein dauerhaftes Leichentuch.",
	L"Erh\u00F6ht deinen Luftzauber um 50%.",
	L"Erh\u00F6ht deinen Erdzauber um 50%.",
	L"Erh\u00F6ht deinen Feuerzauber um 50%.",
	L"Erh\u00F6ht deinen Wasserzauber um 50%.",
	L"Erh\u00F6ht deinen Angriff um 1.",
	L"Erh\u00F6ht dein Einkommen um 250 Gold pro Tag. Erh\u00F6ht deinen Angriff um 3.",
	L"Erh\u00F6ht dein Einkommen um 250 Gold pro Tag. Erh\u00F6ht deinen Angriff um 3.",
	L"Erh\u00F6ht dein Einkommen um 250 Gold pro Tag. Erh\u00F6ht deine Verteidigung um 3.",
	L"Erh\u00F6ht dein Einkommen um 250 Gold pro Tag. Erh\u00F6ht deine Verteidigung um 3. Erh\u00F6ht dein Gl\u00FCck um 1.",
	L"Erh\u00F6ht deine Zauberkraft um 1.",
	L"Erh\u00F6ht deine Verteidigung um 2.",
	L"Erh\u00F6ht deine Verteidigung um 2.",
	L"Stellt t\u00E4glich 5 Zauberpunkte wieder her.",
	L"Erh\u00F6ht deinen Angriff um 2.",
	L"Erh\u00F6ht deine Zauberkraft um 1.",
	L"Erh\u00F6ht deinen Fernkampf um 15% und die Verteidigung deiner Sch\u00FCtzen um 3.",
	L"Erh\u00F6ht deine Verteidigung um 1.",
	L"Erh\u00F6ht deine Verteidigung und die der Goblins um 2.",
	L"Erh\u00F6ht deine Moral und dein Gl\u00FCck um 1.",
	L"Erh\u00F6ht deine Verteidigung um 2 und die der Zwerge um 4.",
	L"Erh\u00F6ht deine Verteidigung um 2.",
	L"Erh\u00F6ht deine Verteidigung um 2 und die der Oger um 4.",
	L"Unendliche Sch\u00FCsse f\u00FCr Fernk\u00E4mpfer.",
	L"Erh\u00F6ht deinen und den Angriff der Zwerge um 3.",
	L"Erh\u00F6ht deine Verteidigung um 2 und deine Bewegungspunkte um 15%.",
	L"Erh\u00F6ht deine Verteidigung um 2 und verringert die gegnerische Moral um 2.",
	L"Erh\u00F6ht deine Verteidigung um 3 und verringert die gegnerische Moral um 1.",
	L"Erh\u00F6ht deine Verteidigung um 3 und verringert deine Moral um 1.",
	L"Erh\u00F6ht deine Zauberkraft um 1 und deinen Schaden um 15%.",
	L"Der Fernkampfschaden wird nicht verringert.",
	L"Erh\u00F6ht deine Bewegungspunkte auf Land um 25 Punkte.",
	L"Verringert die Geschwindigkeit der gegnerischen Einheiten im Kampf um 2.",
	L"Wenige",
	L"Mehrere",
	L"Meute",
	L"Viele",
	L"Horde",
	L"Pulk",
	L"Schwarm",
	L"Legion",
	L"nur wenige",
	L"Mehrere",
	L"eine Meute",
	L"Viele",
	L"eine Horde",
	L"ein Pulk",
	L"ein Schwarm",
	L"eine Legion",
	L"Bauer",
	L"Bauern",
	L"Bauern",
	L"Bogesch\u00FCtze",
	L"Bogesch\u00FCtzen",
	L"Bogesch\u00FCtzen",
	L"Pikenier",
	L"Pikeniere",
	L"Pikeniere",
	L"M\u00F6nch",
	L"M\u00F6nche",
	L"M\u00F6nche",
	L"Kavallerist",
	L"Kavalleristen",
	L"Kavalleristen",
	L"Paladin",
	L"Paladine",
	L"Paladine",
	L"Goblin",
	L"Goblins",
	L"Goblins",
	L"Ork",
	L"Orks",
	L"Orks",
	L"Wolfsreiter",
	L"Wolfsreiter",
	L"Wolfsreiter",
	L"Oger",
	L"Oger",
	L"Oger",
	L"Troll",
	L"Trolle",
	L"Trolle",
	L"Zyklop",
	L"Zyklopen",
	L"Zyklopen",
	L"Junger Magier",
	L"Junge Magier",
	L"Junge Magier",
	L"Weisser Wolf",
	L"Weissen W\u00F6lfe",
	L"Weissen W\u00F6lfe",
	L"Lebende R\u00FCstung",
	L"Lebenden R\u00FCstungen",
	L"Lebenden R\u00FCstungen",
	L"Pegasus",
	L"Pegasi",
	L"Pegasi",
	L"Magier",
	L"Magier",
	L"Magier",
	L"Thor",
	L"Thore",
	L"Thore",
	L"Zentaurus",
	L"Zentauren",
	L"Zentauren",
	L"Wasserspeier",
	L"Wasserspeier",
	L"Wasserspeier",
	L"Greif",
	L"Greifen",
	L"Greifen",
	L"Minotaurus",
	L"Minotauren",
	L"Minotauren",
	L"Hydra",
	L"Hydren",
	L"Hydren",
	L"Roter Drache",
	L"Rote Drachen",
	L"Rote Drachen",
	L"Fee",
	L"Feen",
	L"Feen",
	L"Zwerg",
	L"Zwerge",
	L"Zwerge",
	L"Elf",
	L"Elfen",
	L"Elfen",
	L"Druide",
	L"Druiden",
	L"Druiden",
	L"Einhorn",
	L"Einh\u00F6rner",
	L"Einh\u00F6rner",
	L"Phoenix",
	L"Phoenixe",
	L"Phoenixe",
	L"Skelett",
	L"Skelette",
	L"Skelette",
	L"Zombie",
	L"Zombies",
	L"Zombies",
	L"Lich",
	L"Liche",
	L"Liche",
	L"Vampir",
	L"Vampire",
	L"Vampire",
	L"Schwarzer Ritter",
	L"Schwarze Ritter",
	L"Schwarze Ritter",
	L"Plage",
	L"Plagen",
	L"Plagen",
	L"Dieb",
	L"Diebe",
	L"Diebe",
	L"Nomade",
	L"Nomaden",
	L"Nomaden",
	L"Geist",
	L"Geister",
	L"Geister",
	L"Dschin",
	L"Dschinis",
	L"Dschinis",
	L"Medusa",
	L"Medusen",
	L"Medusen",
	L"Erdelement",
	L"Erdelemente",
	L"Erdelemente",
	L"Luftelement",
	L"Luftelemente",
	L"Luftelemente",
	L"Feuerlement",
	L"Feuerlemente",
	L"Feuerelemente",
	L"Wasserelement",
	L"Wasserelemente",
	L"Wasserelemente",
	L"Matsch",
	L"Mauer",
	L"Turm",
	L"Br\u00FCcke",
	L"Katapult",
	L"Feuert zwei Sch\u00FCsse in jedem Fernkampfangriff",
	L"Teilt zwei Schl\u00E4ge pro Angriff aus",
	L"Erleidet keinen Nachteil im Nahkampf",
	L"Keine feindliche Vergeltung",
	L"F\u00FChrt einen Gegenschlag gegen eine unbegrenzte Anzahl von Angreifern aus",
	L"Zwei Hex-Feld Angriffe",
	L"Greift alle angrenzenden feindlichen Truppen an",
	L"Attackiert aus der Entfernung mit einer Todeswolke die Schaden im Ziel Hex-Feld verursacht. Au\u00DFerdem werden alle lebenden Kreaturen in angrenzenden Hex-Feldern angegriffen.",
	L"Untote Kreatur",
	L"Leblose Kreatur",
	L"Regeneriert Lebenspunkte in jeder Kampfrunde",
	L"Bringt einen extra Wirkungsschaden(+5% pro gereistem Hex-Feld zur angegriffenen Kreatur) wenn in der Schlacht aufgeladen.",
	L"Immun gegen Luftmagiezauber",
	L"Immun gegen Erdmagiezauber",
	L"Immun gegen Feuermagiezauber",
	L"Immun gegen Wassermagiezauber",
	L"Hat  40% Magiewiderstand, was dir die Chance gibt, die Auswirkungen eines feindlichen Zauberangriffs zu ignorieren.",
	L"Nimmt nur 25% Schaden von Zauberangriffen",
	L"Get\u00F6tete Einheiten werden zu Geistern",
	L"Hat eine 10%-ige Chance, die H\u00E4lfte der Gegner zu zerst\u00F6ren",
	L"Belebt Einheiten der eigenen Truppe wieder, indem er Leben in der gleichen Menge auff\u00FCllt, wie er Schaden an anderen verursacht.",
	L"Castellatus",
	L"Starkmauer",
	L"Kanan",
	L"Linderhoff",
	L"Whitemoon",
	L"Yaroslavl",
	L"Middleheim",
	L"Brettonia",
	L"Alexandretta",
	L"Whitestone",
	L"Claxton",
	L"Armitage",
	L"Shinnon",
	L"Gateway",
	L"Dunwall",
	L"Kildare",
	L"Kragg",
	L"Jimstadt",
	L"Hartgrim",
	L"Sandflash",
	L"Morganheim",
	L"Cragmoor",
	L"Dragonspire",
	L"Battlement",
	L"Bocc",
	L"Stropkov",
	L"Tormina",
	L"Dolere",
	L"Rockwarren",
	L"Strongglen",
	L"Kruber",
	L"Rovener",
	L"Tutanberg",
	L"Stronggale",
	L"Corona",
	L"Silverwing",
	L"Facture",
	L"Cloudfire",
	L"Cloudspire",
	L"Equinox",
	L"Athenaeum",
	L"Valtara",
	L"Tirith",
	L"Fallen Star",
	L"Mystos",
	L"Ayer",
	L"Silverspire",
	L"Manufactury",
	L"Veks",
	L"Sorrow Crown",
	L"Chillwater",
	L"Deepshadow",
	L"Darkhold",
	L"Blindroot",
	L"Shadowden",
	L"Scar",
	L"Malev",
	L"Castigare",
	L"Dukered",
	L"Shade",
	L"Evernight",
	L"Darkburrow",
	L"Lost Hold",
	L"Coldshadow",
	L"Starmino",
	L"Grigorov",
	L"Sigman",
	L"Still Water",
	L"Elfwind",
	L"Sebian",
	L"Ceiliedgh",
	L"Gladeroot",
	L"Avalon",
	L"Rainhaven",
	L"Strongglen",
	L"Marishen",
	L"Bath'iere",
	L"",
	L"Emerald Moor",
	L"Wild Willow",
	L"Haunt's Wind",
	L"Cessacioun",
	L"Agony",
	L"Victorash",
	L"Terminus",
	L"Lun\u00EDk IX",
	L"Sandro",
	L"Grave Raven",
	L"Dark Cloud",
	L"Coldsoul",
	L"Letanovce",
	L"Dark Eternal",
	L"Ghostwind",
	L"Blight",
	L"Shady Sands",
	L"Wolfengrott",
	L"Magischer Pfeil",
	L"Schutz vor Erde",
	L"Eile",
	L"Schild",
	L"St\u00F6rstrahl",
	L"Blitz",
	L"Pr\u00E4zision",
	L"Luftschild",
	L"Heiliges Wort",
	L"Gegenschlag",
	L"Auferstehung",
	L"Luftelementarwesen",
	L"Schutz vor Luft",
	L"Verlangsamung",
	L"Steinhaut",
	L"Visionen",
	L"Erdbeben",
	L"Verzweiflung",
	L"Meteorschauer",
	L"Stadttor",
	L"Implosion",
	L"Erdelementarwesen",
	L"Blutdurst",
	L"Schutz vor Wasser",
	L"Fluch",
	L"Blenden",
	L"Schw\u00E4che",
	L"Todeswelle",
	L"Feuerball",
	L"Ungl\u00FCck",
	L"Tote beleben",
	L"Feuersto\u00DF",
	L"Armageddon",
	L"Feuerelementarwesen",
	L"Segen",
	L"Schutz vor Feuer",
	L"Aufheben",
	L"Heilung",
	L"K\u00E4ltestrahl",
	L"Gl\u00FCckspilz",
	L"Frohsinn",
	L"Eisring",
	L"Anti-Magie",
	L"Gebet",
	L"Wasserelementarwesen",
	L"Feen beschw\u00F6ren",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*10).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*10).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*12).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*15).",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle befreundeten Einheiten, indem der Schaden des Erdzaubers um 50% reduziert wird.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 5.",
	L"Steigert die Geschwindigkeit aller eigenen Einheiten um 5.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 15% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 15% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 30% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Nahkampf-Angriffen um 30% reduziert wird.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 3. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 3. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 4. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 5. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*25).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*25).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*27).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*30).",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 3.",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 3.",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 5.",
	L"Steigert den Fernkampfschaden aller befreundeten Einheiten um 5.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 25% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 25% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 50% reduziert wird.",
	L"Sch\u00FCtzt alle befreundeten Einheiten, indem der Schaden von Fernkampf-Angriffen um 50% reduziert wird.",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*10).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*10).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*12).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*15).",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen einen zus\u00E4tzlichen Angriff jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen einen zus\u00E4tzlichen Angriff jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen zwei zus\u00E4tzliche Angriffe jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen drei zus\u00E4tzliche Angriffe jede Runde",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*40).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*40).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*45).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*50).",
	L"Erlaubt es Dir, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*3). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*3). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*4). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*5). Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Luftzaubern um 50% reduziert wird.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 6.",
	L"Verringert die Geschwindigkeit aller feindlichen Einheiten um 6.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 6.",
	L"Erh\u00F6ht die Verteidigungsst\u00E4rke aller befreundeten Einheiten um 6.",
	L"Gibt dir eine genaue Anzahl der umherwandernden Monster und sagt dir, ob Sie deinem Helden folgen m\u00F6chten. Erlaubt dir die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es dein eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt dir eine genaue Anzahl der umherwandernden Monster und sagt dir, ob Sie deinem Helden folgen m\u00F6chten. Erlaubt dir die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es dein eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt dir eine genaue Anzahl der umherwandernden Monster und sagt dir, ob Sie deinem Helden folgen m\u00F6chten. Erlaubt dir die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es dein eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt dir eine genaue Anzahl der umherwandernden Monster und sagt dir, ob Sie deinem Helden folgen m\u00F6chten. Erlaubt dir die Prim\u00E4ren Fertigkeitsstatistiken und Anzahleines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es dein eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Besch\u00E4digt im Kampf wahllos zwei Abschnitte der Burgmauer",
	L"Besch\u00E4digt im Kampf wahllos zwei Abschnitte der Burgmauer",
	L", {Besch\u00E4digt im Kampf wahllos drei Abschnitte der Burgmauer",
	L"Besch\u00E4digt im Kampf wahllos vier Abschnitte der Burgmauer",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 2.",
	L"Veringert die Moral aller feindlichen Einheiten um 2.",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*25).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*25).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*27).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*30).",
	L"Teleportiert deinen Helden in die n\u00E4chste eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert deinen Helden in die n\u00E4chste eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert deinen Helden in jede eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert deinen Helden in jede eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*70).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*70).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*75).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*80).",
	L"Erlaubt es Dir, ein Erdelementarwesen herbeizurufen (St\u00E4rke*3). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Erdelementarwesen herbeizurufen (St\u00E4rke*3). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Erdelementarwesen herbeizurufen (St\u00E4rke*4). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Erdelementarwesen herbeizurufen (St\u00E4rke*5). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 3.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 3.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 6.",
	L"Steigert den Nahkampfschaden, der durch alle feundlichen Einheiten verursacht wird um 6.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle freundlichen Einheiten, indem der Schaden von Wasser Zaubern um 50% reduziert wird.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass alle feindlichen Einheiten im Kampf nur geringen Schaden verursachen.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit der H\u00E4lfte der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit der H\u00E4lfte der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit einem Viertel der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen und keinen Gegenschlag mehr ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 6.",
	L"Veringert die Angriffs-St\u00E4rke aller feindlichen Einheiten um 6.",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*5).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*5).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen nicht untoten Einheiten Schaden zuf\u00FCgt (St\u00E4rke*7).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*10).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*15).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*15).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*17).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*20).",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 2.",
	L"Veringert das Gl\u00FCck aller feindlichen Einheiten um 2.",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*40).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*40).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*45).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*50).",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*15). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*15). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*17). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*20). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*40).",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*40).",
	L"Feuer regnet  auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*45).",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*50).",
	L"Erlaubt es Dir, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*4), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*5), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass alle eigenen Einheiten auf dem Schlachtfeld maximalen Schaden verursachen.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden des Feuerzaubers um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Feuerzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Feuerzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Feuerzaubern um 50% reduziert wird.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen oder feindlichen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von allen Einheiten auf dem Schlachtfeld.",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*5).",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*5).",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*7).",
	L"Entfernt alle negativen Zauber Auswirkungen und heilt eine kleine Menge an Trefferpunkten aller befreundeten Einheiten (St\u00E4rke*7).",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*20)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*20)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*22)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*25)",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 1.",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 1.",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 2.",
	L"Steigert das Gl\u00FCck aller eigenen Einheiten um 2.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 1.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 1.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 2.",
	L"Steigert die Moral aller freundlichen Einheiten um 2.",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*10)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*10)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*12)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*15)",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern.",
	L"Du erh\u00E4lst auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 2.",
	L"Du erh\u00E4lst auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 2.",
	L"Du erh\u00E4lst auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 4.",
	L"Gibt Dir auf alle eigenen Einheitenein einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 4.",
	L"Erlaubt es Dir, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*4), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Dir, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*5), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es dir, Feen zu beschw\u00F6ren (Power*5).",
	L"Erlaubt es dir, Feen zu beschw\u00F6ren (Power*5).",
	L"Erlaubt es dir, Feen zu beschw\u00F6ren (Power*7).",
	L"Erlaubt es dir, Feen zu beschw\u00F6ren (Power*10).",
	L"Nach einem gro\u00DFz\u00FCgigen Trinkgeld fl\u00FCstert der Wirt zu dir:",
	L"Ein weiser Mann hat einst gesagt: \"Teile deine Weisheit mit niemanden.\"",
	L"Speicher dein Spiel bevor du die Hexenh\u00FCtte besuchst.",
	L"Teile deine Fernk\u00E4mpfer wenn du gegen selbige k\u00E4mpfst.",
	L"Finde den Gral. Er ist m\u00E4chtiger als du dir vorstellen kannst.",
	L"Sch\u00FCtze im Kampf immer deine Fernkampfeinheiten.",
	L"Manchmal ist der beste Weg eine Niederlage zu vermeiden den Kampf zu umgehen.",
	L"Greife da an, wo Dein Gegner schwach ist.",
	L"Es ist besser die schweren K\u00E4mpfe mit deinem besten Helden zu bestreiten.",
	L"Versuche die gegnerischen Bewegungen vorherzusehen.",
	L"Beim Reisen durch die W\u00FCste halte nach Oasen ausschau. Sie werden deine Reise beschleunigen.",
	L"Es gibt Sicherheit in den Zahlen, besonders wenn jene Zahlen in den Tausenden sind!",
	L"Wenn du Elfen hast und dein Gegner stark aber langsam ist, lauf herum.",
	L"Bek\u00E4mpfe Feuer mit Schutz vor Feuer",
	L"Trolle mit Steinhaut sind eine der st\u00E4rksten Kreaturen.",
	L"Beschw\u00F6re Pr\u00E4zision und Segnen auf deine Fernk\u00E4mpfer.",
	L"Verwende Steinhaut wenn deine Kreaturen von T\u00FCrmen angeriffen werden.",
	L"Schwarze Drachen sind die m\u00E4chtigsten Kreaturen der Gew\u00F6lbe.",
	L"Die Phoenixe sind die st\u00E4rksten Kreaturen des Waldes.",
	L"Kreaturen der unteren Stufen verlangsamen dich.",
	L"Hey, mir sind die Ger\u00FCchte ausgegangen, weil Leute wie DU nicht oft genug vorbei kommen, um sie mit mir zu teilen!",
	L"Lass deine Kavalerie durch die feindlichen Truppen reiten. Du wirst das Resultat m\u00F6gen. Es ist bedeutend besser.",
	L"Ich habe einmal einen Zwerg gesehen, der gegen Zauber immun war.",
	L"Die Truppe, die auf dem Schlachtfeld den ersten Schlag ausf\u00FChrt, gewinnt meistens.",
	L"Auf dem Schlachtfeld ist Geschwindigkeit Leben und Leben Geschwindigkeit.",
	L"Ich habe sterbende Vampire gesehen, die in dem Blut gefallender Feinde wiedergeboren wurden.",
	L"Es ist unm\u00F6glich Vergeltung auszu\u00FCben, angesichts des furchterregenden Angriffs eines Vampires.",
	L"Der Angriff eines Lichs zerrei\u00DFt die Lebenden, w\u00E4hrend er die Toten unber\u00FChrt l\u00E4\u00DFt.",
	L"Auf dem Schlachtfeld erzeugen Knochen-Drachen Furcht in den Herzen ihrer Feinde.",
	L"Golems haben keinen eigenen Verstand.",
	L"Golems werden durch die magischen Mittel belebt, die den meisten Leuten unbekannt sind.",
	L"Die Kombination aus Drachen und dem Zauberspruch Armageddon ist sehr t\u00F6dlich.",
	L"Titanen werden Schwarze Drachen mit mehr Grausamkeit angreifen als jeder andere.",
	L"Viele f\u00FCrchten den versteinernden Angriff der Medusa. Du solltest mehr ihre goldenen Pfeile f\u00FCrchten.",
	L"Sogar gegen \u00FCberw\u00E4ltigende \u00DCbermacht, feiert der Minotaure im Blutdurst des Kampfes.",
	L"Die F\u00E4higkeiten Logistik und Wegfindung sind wichtig.",
	L"Versuche nicht nutzlose Armeen zu kaufen.",
	L"Es ist unm\u00F6glich einen Angriff gegen die vielk\u00F6pfige Hydra zu vergelten.",
	L"Einige glauben, dass jede Necropolis einen \"Nekromantie Verst\u00E4rker\" baut, der ihren Helden hilft die Toten auferstehen zu lassen.",
	L"Helden, die die \"Halle der Vorfahren\" in einer Festung besuchen, werden bessere Krieger.",
	L"Beitreten.",
	L"Erstellen",
	L"Start!",
	L"Bereit",
	L"Profil...",
	L"Fehler",
	L"Verbindung fehlgeschlagen. Bitte versuchen Sie es sp\u00E4ter noch einmal",
	L"Spieler entfernt",
	L"%s wurde entfernt und ersetzt durch Computerspieler.",
	L"Spiel abgebrochen",
	L"Host hat beschlossen das Spiel abzubrechen.",
	L"Anmelden nicht m\u00F6glich",
	L"User ID ung\u00FCltig.",
	L"Sie nehmen an einem Spiel teil",
	L"M\u00F6chten Sie fortfahren?",
	L"Spiel existiert nicht mehr.",
	L"Spiel voll.",
	L"Beitreten nicht m\u00F6glich",
	L"Erstellen nicht m\u00F6glich",
	L"Das Spiel, an dem Sie teilgenommen haben, ist beendet.",
	L"Speicherstand hochladen...",
	L"Speicherstand runterladen..",
	L"Verbinden zum Server...",
	L"Netz nicht verf\u00FCgbar",
	L"Spieler inm Lobby",
	L"Neuer Mensch im Spiel!",
	L"Bitte, warten f\u00FCr andere Spieler um beizutreten!",
	L"%s Spieler (AI) ist mit %s (Mensch) ersetzt.",
	L"Checking for updates...",
	L"Update available",
	L"Would you like to update now?",
	L"Updating...",
	L"The game will now restart to complete update process",
	L"",
	L"",
	L"Sind Sie sicher, dass Sie %s aus dem Spiel rausschmeisen wollen?",
	L"Der Host hast Sie aus dem Spiel raugeschmiesen."};
